### ISSUE TITLE
[CUSA04907]: Pinball FX3

### ISSUE THREAD

**Issue by RandyB3003** [SysRay/psOff_compatibility#101]
### Please, describe what you get

Game gets stuck on a loading screen.

Emulator version: v.0.5-preview-0
Config logging.json loaded successfully
Config graphics.json loaded successfully
Config controls.json loaded successfully
Config audio.json loaded successfully
Config general.json loaded successfully
Config resolve.json loaded successfully
[1] eboot.bin| Image allocation, addr:0x10000000 size:0x00f72000
[2] libSceFios2.prx| Image allocation, addr:0x10f80000 size:0x0018e000
[3] libc.prx| Image allocation, addr:0x11110000 size:0x000fa000
Selected GPU:NVIDIA GeForce RTX 3070 api:1.3.242
Error:todo sceSystemServiceHideSplashScreen

### Game version you are using

1.06

### Current game status

Intro

### Your emulator version

v.0.4 beta

### Upload your log there

No logs :(

### Upload your screenshots there

![Pinball FX3 not working](https://github.com/SysRay/psOff_compatibility/assets/121063359/1cf36a7f-b8d3-46c0-a611-c1e2d90dd71c)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by RandyB3003** [comment]
[20240419-184022.000.zip](https://github.com/SysRay/psOff_compatibility/files/15046536/20240419-184022.000.zip)

**Comment by RandyB3003** [comment]
Sounds like it reaches Pinball lane but crashed. Has sound only and text boxes!
[20240421-100449.000.zip](https://github.com/SysRay/psOff_compatibility/files/15052806/20240421-100449.000.zip)

**Comment by SysRay** [comment]
Couldn't generate shader: fs_0xa7c2080f
Can you post the console output aswell pls? Only the end, where the shader generation fails.

**Comment by RandyB3003** [comment]
Are you looking for this? This was written at the end when it crashed
Critical Error:Couldn't generate shader: fs_0xcf70d34b
Exiting
saving config files
shutting down VideoOut
deinit Graphics| closed: command buffer watcher
deinit Graphics| done
deinit Graphics| closing command processors
-> destruct CommandProcessor[0]
<- destruct CommandProcessor[0]
deinit Graphics| done
deinit Graphics| closing manager
-> deinit ShaderManager
<- deinit ShaderManager
-> deinit SamplerManager
<- deinit SamplerManager
-> deinit PipelineManager

**Comment by RandyB3003** [comment]
![Pinball FX3 not working2](https://github.com/SysRay/psOff_compatibility/assets/121063359/f1d5aed3-b4a1-4c94-a742-2a97c2c844d0)

**Comment by RandyB3003** [comment]
![Pinball FX3 not working but renders ball](https://github.com/SysRay/psOff_compatibility/assets/121063359/e2715da3-372c-4f3e-bb70-4fa6501f7195)

![Pinball FX3 error](https://github.com/SysRay/psOff_compatibility/assets/121063359/1f626dff-d772-47fe-90c7-6c1fc0931bbf)


[20240427-134228.000.zip](https://github.com/SysRay/psOff_compatibility/files/15139922/20240427-134228.000.zip)
