### ISSUE TITLE
[CUSA07572]: GEM SMASHERS

### ISSUE THREAD

**Issue by RandyB3003** [SysRay/psOff_compatibility#102]
### Please, describe what you get

Crashes after intro.

Emulator version: v.0.5-preview-0
Config logging.json loaded successfully
Config graphics.json loaded successfully
Config audio.json loaded successfully
Config resolve.json loaded successfully
Config general.json loaded successfully
Config controls.json loaded successfully
[1] eboot.bin| Image allocation, addr:0x10000000 size:0x002c2000
[2] libc.prx| Image allocation, addr:0x102d0000 size:0x000e6000
[3] libSceFios2.prx| Image allocation, addr:0x103c0000 size:0x0018e000
[4] libSceNpToolkit.prx| Image allocation, addr:0x10550000 size:0x000b6000
[5] libSceNgs2.prx| Image allocation, addr:0x10610000 size:0x0006a000
[6] libSceAvPlayer.prx| Image allocation, addr:0x10680000 size:0x00046000
Selected GPU:NVIDIA GeForce RTX 3070 api:1.3.242
Console:---------------------- _prologRegistered class: VPList
Console:Registered class: IVObjectComponent
Console:Registered class: VisObject3D_cl
Console:Registered class: VisPath_cl
Console:Registered class: VisBaseEntity_cl
Console:Registered class: AnimEntity_cl
Console:Registered class: VSimpleAnimationComponent
Console:Registered class: PathCameraEntity
Console:Registered class: CameraPositionEntity
Console:Registered class: CustomAnimatedEntity
Console:Registered class: VSoundObject
Console:Registered class: GS_TheWreckBoss
Console:Registered class: GS_PoseidoniaBoss
Console:Registered class: GS_PlayerWorldMap
Console:Registered class: GS_Player_cl
Console:Registered class: GS_Object_cl
Console:Registered class: GS_NorthRockBoss
Console:Registered class: GS_GreenHillBoss
Console:Registered class: GS_GougTreeBoss
Console:Registered class: GS_Friend
Console:Registered class: GS_EggIslandBoss
Console:Registered class: GS_DeepMarshBoss
Console:Registered class: GS_Death
Console:Registered class: GS_Boss_cl
Console:Registered class: GS_BonusPoints_cl
Console:Registered class: GS_BonusPlayerEffects_cl
Console:Registered class: GS_BonusLevelEffects_cl
Console:Registered class: GS_BonusBlockEffects_cl
Console:Registered class: GS_Bonus_cl
Console:Registered class: GS_BoneDesertBoss
Console:Registered class: GS_BlockWallMove
Console:Registered class: GS_BlockWall
Console:Registered class: GS_BlockEnemy
Console:Registered class: GS_BlockEffects
Console:Registered class: GS_BlockDiamond
Console:Registered class: GS_BlockChangeColor
Console:Registered class: GS_BlockBounce
Console:Registered class: GS_Block_cl
Console:Registered class: GS_BlockNull
Console:# Allocate (132c2e60,66576[byte])
Console:# Allocate (132d3280,99240[byte])
Console:# Allocate (132eb640,1443320[byte])
Console:Audio out started (port#1,256[samples],48000[Hz],8[ch])
Console:  Buffer[0] : 13d9fd50
Console:  Buffer[1] : 13da7d50
Error:todo sceSystemServiceHideSplashScreen
Error:todo sceSaveDataDirNameSearch

### Current game status

Intro

### Your emulator version

v.0.5-preview-0

### Upload your log there

[20240419-180525.000.zip](https://github.com/SysRay/psOff_compatibility/files/15046471/20240419-180525.000.zip)

### Upload your screenshots there

![GEM SMASHER crash PSoff](https://github.com/SysRay/psOff_compatibility/assets/121063359/bcc86af2-eca5-4358-b906-b36f59f2a5b5)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by RandyB3003** [comment]
Crashes at same point.

![GEM SMASHER crash PSoff new crash](https://github.com/SysRay/psOff_compatibility/assets/121063359/995fb79e-7faf-49ea-ba12-71ea1355ed61)

[20240420-081232.000.zip](https://github.com/SysRay/psOff_compatibility/files/15048729/20240420-081232.000.zip)

**Comment by igor725** [comment]
Should progress further with <https://github.com/SysRay/psOff_public/actions/runs/8772042055>

**Comment by RandyB3003** [comment]
Goes to white screen and hangs.

![white screen GEM SMASHER progress](https://github.com/SysRay/psOff_compatibility/assets/121063359/da28dd18-24c0-4fd5-a2fa-d174d797be63)

[20240421-094535.000.zip](https://github.com/SysRay/psOff_compatibility/files/15052763/20240421-094535.000.zip)

**Comment by RandyB3003** [comment]
white screen again.

[20240421-122856.000.zip](https://github.com/SysRay/psOff_compatibility/files/15053276/20240421-122856.000.zip)
