### ISSUE TITLE
[CUSA23265]: Need for Speed™ Hot Pursuit Remastered

### ISSUE THREAD

**Issue by Ordinary205** [SysRay/psOff_compatibility#108]
### Please, describe what you get

Crashes.

Error:Couldn't Allocate Host Memory: 0x225160000|52445184 type:50 result:VK_ERROR_OUT_OF_DEVICE_MEMORY
Console:Allocating onionPool Runtime of size 50 MB
Console:ERROR: Allocating onionPool Runtime of size 50 MB
Console:Post AllocateOnion : direct memory remaining 0 MB
Console:----------------------------------------------------------------
Console:System settings:
Error:0x140022fc7
Error:0x14001eb37
Error:0x140017163
Error:0x006330e8
Critical Error:Missing Symbol| Name:rTIV11nMQuM#h#i Lib:libSceGnmDriver(ver:1) Mod:libSceGnmDriver(major:1 minor:1)
Exiting

### Game version you are using

v1.03

### Current game status

Nothing

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

b0185a61520ae59fa5833f1225ef286dede9921c

### Upload your log there

[20240420-104800.000.zip](https://github.com/SysRay/psOff_compatibility/files/15047201/20240420-104800.000.zip)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by gandalfthewhite19890404** [comment]
Resolved - sceGnmValidateOnSubmitEnabled

**Comment by Ordinary205** [comment]
New Error:

Console:    Shader write mask = 0x0000000f
Console:    Shader write mask = 0x0000000f
Console:    Shader write mask = 0x0000000f
Console:    Shader write mask = 0x0000000f
Console:    Shader write mask = 0x0000000f
Error:todo sceNpUnregisterStateCallbackA
Error:Exception 0x105bd4b5
Error:0x140022fc7
Error:0x14001eb37
Error:0x140019447
Error:0x140063079
Error:0x7ffdc38923af
Error:0x7ffdc38414b4
Error:0x7ffdc3890ebe
Error:0x105bd4b5          in eboot.bin
Error:Access violation: Read 0x00000040 
[20240426-063711.000.zip](https://github.com/SysRay/psOff_compatibility/files/15124654/20240426-063711.000.zip)
