### ISSUE TITLE
[CUSA01661]: J-Stars Victory Vs+

### ISSUE THREAD

**Issue by Emulator-Team-2** [SysRay/psOff_compatibility#110]
### Please, describe what you get

The game crashes right away due to an access violation error.
```
Error:Alloc Error| len:0xfffffffeef000000 alignment:0x00200000 memorytype:0 err:0
Error:Exception 0x103ea8e6
Error:0x140022fc7
Error:0x14001eb37
Error:0x140019447
Error:0x140063079
Error:0x7ffdd7893cff
Error:0x7ffdd780e456
Error:0x7ffdd7892cee
Error:0x103ea8e6          in eboot.bin
Error:AccessViolationType::Write: 0x103ea8e6
```

### Game version you are using

01.00

### Current game status

Nothing

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

23d69a90645c36ddc6c887842984953a54c53a12

### Upload your log there

[20240420-130107.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/15047894/20240420-130107.000.p7d.zip)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by Emulator-Team-2** [comment]
## Update:

The game still crashes right after launch.
But now with a different error.

Missing symbol:
```
Critical Error:Missing Symbol| Name:3KOuC4RmZZU#Y#Z Lib:libSceNpSignaling(ver:1) Mod:libSceNpSignaling(major:1 minor:1)
Exiting
```
```
VideoOut| Destroy vulkan
Critical Error:Access violation: Execute at addr:0x00000000 info:0x00000000 , module base:0x00000000
Exiting
```

**Current game status:** Nothing.

**Emulator version:** v.0.5-nightly_29.04.24-fix 
**psOff-libs version:**
ef8106ac3611135c30ef7ac92ec8b11b124b1f11

Log:
[20240502-161555.001.zip](https://github.com/SysRay/psOff_compatibility/files/15189603/20240502-161555.001.zip)

**Comment by gandalfthewhite19890404** [comment]
Missing - sceNpSignalingInitialize

**Comment by GamingDucking** [comment]
Retest in the latest version

**Comment by Emulator-Team-2** [comment]
## Update:

Still crashes right after launch.
But now, due to an unknown Imagedim error.
```
Error:todo handle attributes
Error:TODO: sceSharePlayInitialize
Error:TODO: sceSharePlaySetProhibition
Error:todo sceNpSetNpTitleId
Error:todo sceNpMatching2Initialize
Error:todo sceNpRegisterStateCallback
Error:todo sceNpSetContentRestriction
Error:TODO: sceSharePlayGetCurrentConnectionInfo
Error:TODO: sceSharePlayGetCurrentConnectionInfo

unknown Imagedim for 6
```

**Current game status:** Nothing.

**Renderer version:** v.0.5-nightly_29.04.24-fix
**psOff version:**
dcea5cb1f71939292e0bdb40adc7f60fea2d6168

Log:
- Looks like logs is empty? (0 KB).

**Comment by StevenMiller123** [comment]
Now shows distorted copyright screens, then gets stuck rendering flickering gradients. 
![J-Stars 1](https://github.com/SysRay/psOff_compatibility/assets/56742918/921f20d2-6752-4be8-9080-55701387747a)
<img width="639" alt="J-Stars 2" src="https://github.com/SysRay/psOff_compatibility/assets/56742918/5120e268-d43f-4be5-96b0-b12ec59b0e68">
<img width="640" alt="J-Stars 3" src="https://github.com/SysRay/psOff_compatibility/assets/56742918/fdb9ddcb-520f-4904-90a6-0908ed9c981e">

Emulator Version: v.0.5
Log: [J-Stars Log.zip](https://github.com/user-attachments/files/15527502/J-Stars.Log.zip)

**Comment by Emulator-Team-2** [comment]
## Update:

For me, this game still crashes right after launch.
```
libSceAudioOut| Error:todo handle attributes

Couldn't vkQueueSubmit Transfer VK_ERROR_DEVICE_LOST
```

**Current game status:** Nothing.

**Renderer version:** v.0.6-nightly_08.06.2024  
**psOff version:**
98ef80dfdd8554aab5edccb09b56dd41bb1340f6

Log:

- Looks like logs is empty? (0 KB).
