### ISSUE TITLE
[CUSA05169]: Clicker Heroes

### ISSUE THREAD

**Issue by Hermiten** [SysRay/psOff_compatibility#112]
### Please, describe what you get

Crash 
Missing Symbol| Name:Cxwy7wHq4J0#n#N Lib:libSceJson2(ver:1) Mod:libSceJson(major:1 minor:1)

### Game version you are using

v1.0

### Current game status

Nothing

### Your emulator version

https://github.com/SysRay/psOff_public/actions/runs/8764677483

### Upload your log there

[20240420-185652.000.zip](https://github.com/SysRay/psOff_compatibility/files/15049105/20240420-185652.000.zip)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by igor725** [comment]
Should progress further with <https://github.com/SysRay/psOff_public/actions/runs/8772042055>

**Comment by Hermiten** [comment]
New test:

Crash

Console:

> Error:todo sceNpSetContentRestriction
> Error:todo sceSaveDataUmountWithBackup
> Error:todo Initializer
> Error:todo initialize
> Error:todo sceNpRegisterStateCallback
> Console:[IAP] [IAPSTAT_IDLE] -> [IAPSTAT_IDLE]
> Error:todo sceSystemServiceHideSplashScreen
> Console:Loader failed to open '/hostapp//flash.swf'Tag 'DefineBinaryData' (87) is not supported, potentially 'TLF text' fields are used. Switch to 'Classic Text'.NATIVE GetSystemLang()
> todo create for loop -15

Log:
[20240424-152830.000.zip](https://github.com/SysRay/psOff_compatibility/files/15094958/20240424-152830.000.zip)

Version:
https://github.com/SysRay/psOff_public/actions/runs/8806655336
