### ISSUE TITLE
[CUSA02609]: Adventures of Pip

### ISSUE THREAD

**Issue by Hermiten** [SysRay/psOff_compatibility#118]
### Please, describe what you get

crash

### Game version you are using

01.00

### Current game status

Nothing

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

d9ae85aa42a851419cfdd10f78c1d10d8c6d017e

### Upload your log there

[20240420-190517.000.zip](https://github.com/SysRay/psOff_compatibility/files/15049129/20240420-190517.000.zip)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by igor725** [comment]
You're on integrated graphics, it seems. Each of your reports says "out of device memory" when trying to allocate 2GB of VRAM. Your laptop probably won't boot most of the games.

**Comment by gandalfthewhite19890404** [comment]
My retest:
crash

### **Game version you are using**
01.00

### **Current game status**
Nothing

### **Your emulator version**
v.0.5-preview-0

### **psOff-libs version you are using**
53b9bf6

### **Upload your log there**
[20240421-184415.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/15052529/20240421-184415.000.p7d.zip)

**Comment by Hermiten** [comment]
Update label ? :)

**Comment by yaya54840** [comment]
Crash after loading
v.0.6-nightly_03.06.2024

![Capture d'écran 2024-06-04 1
[20240608-145043.000.p7d.zip](https://github.com/user-attachments/files/15748115/20240608-145043.000.p7d.zip)

71313](https://github.com/SysRay/psOff_compatibility/assets/47884186/8cc2f661-b198-4f79-8fac-3441e2998537)
![Capture d'écran 2024-06-08 145120](https://github.com/SysRay/psOff_compatibility/assets/47884186/d1d0eba7-59e3-49d3-9722-33eac3904a65)
![Capture d'écran 2024-06-08 145135](https://github.com/SysRay/psOff_compatibility/assets/47884186/b475e7b4-641d-4586-8004-8bdedf634a62)
