### ISSUE TITLE
[CUSA04480]: NieR:Automata

### ISSUE THREAD

**Issue by igor725** [SysRay/psOff_compatibility#12]
### Please, describe what you get

The game crashes right away with shader generation error:
```
Couldn't find M0(0) for cond:12(Block) (items found:0)
(cs_0x844598a0) Compile error, line:0 column:0 | (Invalid SPIR-V magic number.)
Optimize failed
Critical Error:Couldn't generate shader: cs_0x844598a0
Exiting
```

### Game version you are using

01.00

### Current game status

None

### Version

v.0.4-beta (Default)

### psOff-libs version you are using

31194d322c79004e339a47d203a2f0b3ff8bf8fe

### Upload your log there

[20240408-140252.000.zip](https://github.com/SysRay/psOff_compatibility/files/14904595/20240408-140252.000.zip)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by gandalfthewhite19890404** [comment]
Retest with [84c77ed](https://github.com/SysRay/psOff_public/commit/84c77ed5f0047ca20cfd225ce7784579ece8b5fe)
### **Description**
Boots but crashes after some screens.

### **Current game status**
Intro

### **Logs**
[20240603-062413.000.p7d.zip](https://github.com/user-attachments/files/15528401/20240603-062413.000.p7d.zip)

### **Screenshots**
![image](https://github.com/SysRay/psOff_compatibility/assets/24764335/83a00a0c-8297-449a-8a58-d1662fea51c4)
