### ISSUE TITLE
[CUSA09499]: Cat Quest

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [SysRay/psOff_compatibility#123]
### Please, describe what you get

Crash

### Game version you are using

1.01

### Current game status

Nothing

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

53b9bf6

### Upload your log there

[20240421-183800.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/15052513/20240421-183800.000.p7d.zip)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by igor725** [comment]
Cat Quest now boots and goes ingame, but sometimes it crashes
https://github.com/SysRay/psOff_compatibility/assets/40758030/c0708d98-002b-43ff-94cb-09fdc0ca004c
