### ISSUE TITLE
[CUSA00192]: Worms Battlegrounds

### ISSUE THREAD

**Issue by Digote** [SysRay/psOff_compatibility#128]
### Please, describe what you get

**Nothing**

Error:todo sceSystemServiceHideSplashScreen
Error:Couldn't create ColorAttachment width:0 height:0 result:VK_ERROR_INITIALIZATION_FAILED
Error:0x140022fc7
Error:0x14001eb37
Error:0x140017163
Error:0x00521fe8
Critical Error:Missing Symbol| Name:FzEWeYnAFlI#e#f Lib:libSceContentExport(ver:1) Mod:libSceContentExport(major:1 minor:1)
Exiting

### Game version you are using

1.0

### Current game status

Nothing

### Your emulator version

v0.5-preview-0

### psOff-libs version you are using

https://github.com/SysRay/psOff_public/actions/runs/8710509714

### Upload your log there

[20240422-145229.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/15066973/20240422-145229.000.p7d.zip)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by gandalfthewhite19890404** [comment]
Missing - sceContentExportInit

**Comment by igor725** [comment]
Should progress further with SysRay/psOff_public#142

**Comment by Digote** [comment]
It's like that currently.

https://github.com/SysRay/psOff_public/actions/runs/8902419264

[20240430-195549.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/15172024/20240430-195549.000.p7d.zip)


_________________________________________________________________________________________________________________________

Error:todo sceSystemServiceHideSplashScreen
Error:Couldn't create ColorAttachment width:0 height:0 result:VK_ERROR_INITIALIZATION_FAILED
Error:todo sceGameLiveStreamingInitialize
Error:todo sceGameLiveStreamingGetCurrentStatus
Critical Error:Missing Symbol| Name:9030RnBDoh4#p#p Lib:libScePngEnc(ver:1) Mod:libScePngEnc(major:1 minor:1)
Exiting
saving config files
shutting down VideoOut
deinit Graphics| closed: command buffer watcher
deinit Graphics| done
deinit Graphics| closing command processors
-> destruct CommandProcessor[0]
<- destruct CommandProcessor[0]
deinit Graphics| done
deinit Graphics| closing manager
-> deinit ShaderManager
<- deinit ShaderManager
-> deinit SamplerManager
<- deinit SamplerManager
-> deinit PipelineManager
<- deinit PipelineManager
-> deinit GpuMemoryManager
<- deinit GpuMemoryManager
deinit Graphics| done
deinit ImageHandler
Critical Error:Access violation: Execute at addr:0x00000000 info:0x00000000 , module base:0x00000000
Exiting

**Comment by igor725** [comment]
May progress further now
