### ISSUE TITLE
[CUSA19620]: 13 Sentinels: Aegis Rim

### ISSUE THREAD

**Issue by Digote** [SysRay/psOff_compatibility#129]
### Please, describe what you get

**Nothing.**

Error:todo sceGameLiveStreamingInitialize
Error:0x140022fc7
Error:0x14001eb37
Error:0x140017163
Error:0x027b6a88
Critical Error:Missing Symbol| Name:u4bCGkqhOB4#FOz#e Lib:libSceShareUtility(ver:1) Mod:libSceShareUtility(major:1 minor:1)
Exiting

### Game version you are using

1.0

### Current game status

Nothing

### Your emulator version

v0.5-preview-0

### psOff-libs version you are using

https://github.com/SysRay/psOff_public/actions/runs/8740145253

### Upload your log there

[20240422-145502.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/15066994/20240422-145502.000.p7d.zip)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by gandalfthewhite19890404** [comment]
Missing - sceShareUtilityAdvanceInitialize

**Comment by igor725** [comment]
Should progress further with SysRay/psOff_public#142

**Comment by Digote** [comment]
It's like that currently.

https://github.com/SysRay/psOff_public/actions/runs/8902419264

[20240430-195848.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/15172032/20240430-195848.000.p7d.zip)


___________________________________________________________________________________________________________________________

Error:todo sceGameLiveStreamingInitialize
Error:Couldn't Allocate Host Memory: 0x213030000|8355840 type:51 result:VK_ERROR_OUT_OF_DEVICE_MEMORY
Error:Couldn't Allocate Host Memory: 0x213830000|9437184 type:51 result:VK_ERROR_OUT_OF_DEVICE_MEMORY
Error:Couldn't Allocate Host Memory: 0x214130000|8355840 type:51 result:VK_ERROR_OUT_OF_DEVICE_MEMORY
Error:Couldn't Allocate Host Memory: 0x214b70000|9437184 type:51 result:VK_ERROR_OUT_OF_DEVICE_MEMORY
Error:Couldn't Allocate Host Memory: 0x215470000|8355840 type:51 result:VK_ERROR_OUT_OF_DEVICE_MEMORY
Error:Couldn't Allocate Host Memory: 0x215eb0000|9437184 type:51 result:VK_ERROR_OUT_OF_DEVICE_MEMORY
Critical Error:0x00000000 not in m_deviceMemoryList
Exiting
