### ISSUE TITLE
[CUSA00342]: Murdered: Soul Suspect

### ISSUE THREAD

**Issue by GAMERRPCS3** [SysRay/psOff_compatibility#135]
### Please, describe what you get

Nothing - missing symbol.

Critical Error:Missing Symbol| Name:w5IHyvahg-o#E#F Lib:libScePosix(ver:1) Mod:libkernel(major:1 minor:1)
Exiting

### Game version you are using

01.00

### Current game status

Nothing

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

1842fa1ca926cc505bb2eb96c94888e5d6632c9b

### Upload your log there

[f91pi8d1joxkser2.zip](https://github.com/SysRay/psOff_compatibility/files/15072959/f91pi8d1joxkser2.zip)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by igor725** [comment]
## Update

The game now crashes with this error
```
Emulator version: v.0.5-preview-0
Config resolve.json loaded successfully
Config logging.json loaded successfully
Config graphics.json loaded successfully
Config audio.json loaded successfully
Config general.json loaded successfully
Config controls.json loaded successfully
[1] eboot.bin| Image allocation, addr:0x10000000 size:0x02876000
[2] libSceNgs2.prx| Image allocation, addr:0x20000000 size:0x0006a000
[3] libc.prx| Image allocation, addr:0x30070000 size:0x000e2000
[4] libSceFios2.prx| Image allocation, addr:0x40160000 size:0x0016e000
Selected GPU:NVIDIA GeForce RTX 3060 api:1.3.277
Error:TODO: scePlayGoGetToDoList
Error:pread[-1] file==nullptr: 0x100040710:48
Error:pread[-1] file==nullptr: 0x100040a70:48
Error:pread[-1] file==nullptr: 0x1000423f0:48
Error:todo sceSystemServiceHideSplashScreen
Critical Error:0x00000000 not in m_deviceMemoryList
Exiting
Assertion failed: numElements > 4, file D:\a\psOff\psOff\tools\sb2spirv\lib\src/typeId.h, line 196```
