### ISSUE TITLE
[CUSA04169]: THE LAST BLADE 2

### ISSUE THREAD

**Issue by GAMERRPCS3** [SysRay/psOff_compatibility#137]
### Please, describe what you get

Nothing - missing symbol.

Critical Error:Missing Symbol| Name:whrS4oksXc4#h#f Lib:libSceFont(ver:1) Mod:libSceFont(major:1 minor:1)
Exiting

### Game version you are using

01.00

### Current game status

Nothing

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

1842fa1ca926cc505bb2eb96c94888e5d6632c9b

### Upload your log there

[ns1eonx6d66jrwer.zip](https://github.com/SysRay/psOff_compatibility/files/15073216/ns1eonx6d66jrwer.zip)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by gandalfthewhite19890404** [comment]
Missing - sceFontMemoryInit
