### ISSUE TITLE
[CUSA11253]: Dead Cells

### ISSUE THREAD

**Issue by igor725** [SysRay/psOff_compatibility#14]
### Please, describe what you get

The game survives up to menu, but trying to get ingame crashes the emulator:

```
Mapping is missing for: 28| (0, 0) (4, 4) 
Mapping is missing for: 12| (0, 0) (4, 4)
Mapping is missing for: 32| (0, 0) (4, 4)
Mapping is missing for: 20| (0, 0) (4, 4)
Mapping is missing for: 36| (0, 0) (4, 4)
Mapping is missing for: 12| (0, 0) (4, 4)
```

### Game version you are using

01.00

### Current game status

Intro

### Version

v.0.5-beta

### psOff-libs version you are using

b5074db38b7951ed0c0acff2a9a51841100fa4d3

### Upload your log there

[20240414-134423.000.zip](https://github.com/SysRay/psOff_compatibility/files/14970393/20240414-134423.000.zip)

### Upload your screenshots there

![image](https://github.com/SysRay/psOff_compatibility/assets/40758030/bb24725f-d45e-496d-a7da-b60b448d2ff7)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by yaya54840** [comment]
Hi igor  this game works now
