### ISSUE TITLE
[CUSA15634]: Windjammers 2

### ISSUE THREAD

**Issue by SonicAdventureX** [SysRay/psOff_compatibility#141]
### Please, describe what you get

It boots up beautifully! But it'll kick me out when it tries to show me the title screen.

### Game version you are using

1.00

### Current game status

In-game

### Your emulator version

v.0.5-preview-0

### Upload your log there
[20240423-145604.000.zip](https://github.com/SysRay/psOff_compatibility/files/15081872/20240423-145604.000.zip)

### Upload your screenshots there
Here's the log.
![image](https://github.com/SysRay/psOff_compatibility/assets/39503785/23e24426-3a93-4670-b47c-2c7ea1ad185a)

![image](https://github.com/SysRay/psOff_compatibility/assets/39503785/0a8abd2c-421e-427a-8e54-243253c8bb50)
![image](https://github.com/SysRay/psOff_compatibility/assets/39503785/1883685c-1837-4be7-8c4d-5f77ff6a2c6d)
![image](https://github.com/SysRay/psOff_compatibility/assets/39503785/fa3aac48-4fe5-4fd7-addc-aa752e764112)
![image](https://github.com/SysRay/psOff_compatibility/assets/39503785/ae9ad6ca-6dae-4aa5-b497-0046a9c8b4a2)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by igor725** [comment]
Same as #142

**Comment by SonicAdventureX** [comment]
For sure No problem, buddy

**Comment by SonicAdventureX** [comment]
Yup here's the report to Windjammers 2 just in case you need it also, buddy.

[20240427-094618.000.zip](https://github.com/SysRay/psOff_compatibility/files/15138373/20240427-094618.000.zip)

![image](https://github.com/SysRay/psOff_compatibility/assets/39503785/e23c0e3e-9935-4455-8174-8daa97a4b763)

![image](https://github.com/SysRay/psOff_compatibility/assets/39503785/b2466de5-20d8-4ad3-8b67-4fd95e7dda4a)

**Comment by SonicAdventureX** [comment]
Still no audio but Holy Moses smell the Roses! It goes in-game! ❤️

[20240502-085653.000.zip](https://github.com/SysRay/psOff_compatibility/files/15188635/20240502-085653.000.zip)

![image](https://github.com/SysRay/psOff_compatibility/assets/39503785/644bd97d-d739-4b51-af29-23ed4ae167f1)

![image](https://github.com/SysRay/psOff_compatibility/assets/39503785/88d5db21-b3bf-4e92-813c-6a935b0564cd)
