### ISSUE TITLE
[CUSA00003]: Driveclub

### ISSUE THREAD

**Issue by SonicAdventureX** [SysRay/psOff_compatibility#142]
### Please, describe what you get

It tries to boot up when it goes in black screen but it kicks me right back out.

### Game version you are using

1.00

### Current game status

It goes in black screen when it tries to boot up. Then it'll kick me right back out when it shows me this log.

### Your emulator version

emulator.exe --help

### psOff-libs version you are using

v.0.5-preview-0

### Upload your log there
[20240423-213448.000.zip](https://github.com/SysRay/psOff_compatibility/files/15084984/20240423-213448.000.zip)

### Upload your screenshots there

![image](https://github.com/SysRay/psOff_compatibility/assets/39503785/0912760d-6d2a-435f-ab6c-dcb8ac0d82e5)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by igor725** [comment]
You should upload log file from P7Logs folder to `Upload your logs there` section. Check other issues and fix yours according to rules. Also game's status not "Playable" but "Nothing".
