### ISSUE TITLE
[CUSA43222]: Metal Gear Solid: Master Collection Vol.1 Bonus Content.

### ISSUE THREAD

**Issue by SonicAdventureX** [SysRay/psOff_compatibility#143]
### Please, describe what you get

It boots very well also. But unfortunately, I can't click on the "Agree" browser to continue the game since it can't be high lighted.

### Game version you are using

1.00

### Current game status

Intro

### Your emulator version

emulator.exe --help

### psOff-libs version you are using

v.0.5-preview-0

### Upload your log there

[20240423-185753.000.zip](https://github.com/SysRay/psOff_compatibility/files/15083900/20240423-185753.000.zip)

### Upload your screenshots there

![image](https://github.com/SysRay/psOff_compatibility/assets/39503785/85bbd041-f1c4-48da-9e3d-fd65c550e888)
![image](https://github.com/SysRay/psOff_compatibility/assets/39503785/16595467-ca25-4521-ba2a-e5a0da8a84b9)
![image](https://github.com/SysRay/psOff_compatibility/assets/39503785/bbc1a286-1d13-444f-80cc-4aa2030dfb05)
![image](https://github.com/SysRay/psOff_compatibility/assets/39503785/ec055774-7706-41e8-8603-3d5776ec806b)
![image](https://github.com/SysRay/psOff_compatibility/assets/39503785/8b91c656-3bd7-4480-95d5-499a3ae44675)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by GAMERRPCS3** [comment]
Retest 

Test with update 01.03 the game enters the gameplay. The only current problem is that the sound is missing.

![Capture d’écran 2024-04-24 103044](https://github.com/SysRay/psOff_compatibility/assets/121258975/aa417f90-9426-4495-8085-6bda483a98a9)
![Capture d’écran 2024-04-24 103102](https://github.com/SysRay/psOff_compatibility/assets/121258975/05c373e5-1482-4c9b-abc3-9eb8f94c35a1)
