### ISSUE TITLE
[CUSA06216]: Windjammers

### ISSUE THREAD

**Issue by SonicAdventureX** [SysRay/psOff_compatibility#145]
### Please, describe what you get

The first Windjammers tries to boot up but it kicks me right back out.

### Game version you are using

1.00

### Current game status

Nothing

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

N/A

### Upload your log there

[20240424-110814.000.zip](https://github.com/SysRay/psOff_compatibility/files/15096466/20240424-110814.000.zip)

### Upload your screenshots there

![image](https://github.com/SysRay/psOff_compatibility/assets/39503785/3ecffa24-174e-4ab8-abe6-f7d8a3fd8b88)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by SonicAdventureX** [comment]
No Way! It has buff. Is trying to start up & it shows an DotEmu introduction now ❤️

![image](https://github.com/SysRay/psOff_compatibility/assets/39503785/9fe96c4f-2420-4e19-a892-35d29ff76aae)

**Comment by igor725** [comment]
Provide updated log please

**Comment by SonicAdventureX** [comment]
Oh absolutely. Not a problem buddy.

**Comment by SonicAdventureX** [comment]
Okay I got some amazing news but a slight bad news. The amazing news, is that Tomb Raider 1-2-3 Remastered is longer glitching. The slight bad news is that since the graphics glitching has been fixed from Tomb Raider 1-2-3 Remastered, Windjammers 1 and 2 have this black screen going on. But they're still running though an intro. ❤️

[20240427-093959.000.zip](https://github.com/SysRay/psOff_compatibility/files/15138359/20240427-093959.000.zip)


![image](https://github.com/SysRay/psOff_compatibility/assets/39503785/7b3b336e-e91d-40b7-aae7-d6d8fa2c5cde)

![image](https://github.com/SysRay/psOff_compatibility/assets/39503785/c1f3bfe4-aff1-4256-ae24-02ce7625d2c6)
