### ISSUE TITLE
[CUSA15883]: River City Girls

### ISSUE THREAD

**Issue by SonicAdventureX** [SysRay/psOff_compatibility#147]
### Please, describe what you get

River City Girls tries to boot up, but it kicks me right back out

### Game version you are using

1.00

### Current game status

Nothing

### Your emulator version

emulator.exe --help

### psOff-libs version you are using

v.0.5-preview-0

### Upload your log there

[20240424-111926.000.zip](https://github.com/SysRay/psOff_compatibility/files/15096600/20240424-111926.000.zip)

### Upload your screenshots there

![image](https://github.com/SysRay/psOff_compatibility/assets/39503785/530474a8-7f85-489f-8167-e29ab9c2eadb)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by gandalfthewhite19890404** [comment]
Close, please as duplicate

**Comment by igor725** [comment]
#148
