### ISSUE TITLE
[CUSA15250]: DELTARUNE Chapter 1

### ISSUE THREAD

**Issue by igor725** [SysRay/psOff_compatibility#15]
### Please, describe what you get

This game based on Undertale, so they should share the same issues.

### Game version you are using

01.00

### Current game status

Ingame

### Version

v.0.5-beta

### psOff-libs version you are using

b5074db38b7951ed0c0acff2a9a51841100fa4d3

### Upload your log there

[20240414-135537.000.zip](https://github.com/SysRay/psOff_compatibility/files/14970409/20240414-135537.000.zip)

### Upload your screenshots there

![emulator_2024-04-14_13-56-09](https://github.com/SysRay/psOff_compatibility/assets/40758030/030c9a32-062e-487f-a101-f7e2bceafdab)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by cainan-c** [comment]
Running update v01.03, "DELTARUNE Chapter 1&2" results in the following errors:

Error:Couldn't Allocate GPU Memory: 0x1834c0000|1073741824 type:51 result:VK_ERROR_OUT_OF_DEVICE_MEMORY
Error:Map| Couldn't allocHeap vaddr:0x00000000 physAddr:0x00000001 len:0x40000000 prot:0x33 -> out:0x1834c0000
Console:failed to allocate from 'onion' pool! Reduce usage or increase pool size
Error:Exception 0x20042cf2
Error:0x14001fd27
Error:0x14001bab7
Error:0x140016347
Error:0x14005fd49
Error:0x7ffea679440f
Error:0x7ffea670e466
Error:0x7ffea67933fe
Error:0x200
42cf2          in libc.prx
Error:AccessViolationType::Write: 0x20042cf2

A log file can be found here:
[20240415-180550.000.zip](https://github.com/SysRay/psOff_compatibility/files/14982271/20240415-180550.000.zip)

**Comment by cldgit** [comment]
I beat the first chapter without encountering any issues (which is all of v1.00)
![deltarune-chp1](https://github.com/SysRay/psOff_compatibility/assets/123279742/1221640b-418b-4e92-9327-615089591520)
![deltarune-end](https://github.com/SysRay/psOff_compatibility/assets/123279742/c5d9d7be-be77-4c78-8d1a-900bd669759f)
