### ISSUE TITLE
[CUSA18557]: Zaccaria Pinball

### ISSUE THREAD

**Issue by Hermiten** [SysRay/psOff_compatibility#160]
### Please, describe what you get

Go to menu and then crash when starting a game

### Game version you are using

01.00

### Current game status

Intro

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

c265cf11d925eaaf3d9622a0475d31accd635140

### Upload your log there

[20240426-235533.000.zip](https://github.com/SysRay/psOff_compatibility/files/15135569/20240426-235533.000.zip)

### Upload your screenshots there

<img width="960" alt="image" src="https://github.com/SysRay/psOff_compatibility/assets/151466/655c40e3-2613-44b6-b9a6-52eaeb090208">

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by SysRay** [comment]
Could you please also provide the console output? The last lines above"Couldn't generate shader: fs_0x5b796a94"

**Comment by Hermiten** [comment]
> Could you please also provide the console output? The last lines above"Couldn't generate shader: fs_0x5b796a94"



> SMRD Instruction missing op:6
> Critical Error:Couldn't generate shader: fs_0x4e6c38a
> Exiting
> Critical Error:Couldn't generate shader: fs_0x1852fec7
> Exiting
> Critical Error:Couldn't generate shader: fs_0xfebe70b8
> Exiting
> (fs_0xcb55fb50) Compile error, line:0 column:0 | (Expected Coordinate to have at least 4 components, but given only 3
>   %148 = OpImageSampleImplicitLod %v4float %147 %135
> )
> (fs_0x3317c2ea) Compile error, line:0 column:0 | (Expected Coordinate to have at least 4 components, but given only 3
>   %148 = OpImageSampleImplicitLod %v4float %147 %135
> )
> Optimize failed
> Optimize failed
> Critical Error:Couldn't generate shader: fs_0x3317c2ea
> Exiting
> Critical Error:Couldn't generate shader: fs_0xcb55fb50
> Exiting
> saving config files
> shutting down VideoOut
