### ISSUE TITLE
[CUSA15289]: Slay the Spire

### ISSUE THREAD

**Issue by Digote** [SysRay/psOff_compatibility#169]
### Please, describe what you get

The game seems to work in terms of graphics, but there is no audio.

### Game version you are using

2.0

### Current game status

Ingame

### Your renderer version

v0.5-preview-0

### Your psOff version

https://github.com/SysRay/psOff_public/actions/runs/8942867316

### Upload your log there

[20240503-234523.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/15206419/20240503-234523.000.p7d.zip)

### Upload your screenshots there

https://github.com/SysRay/psOff_compatibility/assets/45742711/71cf21c3-f333-4354-9c67-759f375f7247

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by igor725** [comment]
Well, it doesn't seem like the game should miss the audio... It's weird a bit. There's no Ngs2 in library list and your audio devices opens just fine :/
![image](https://github.com/SysRay/psOff_compatibility/assets/40758030/3c8bc98a-61aa-4a69-b862-22d95dfac213)
