### ISSUE TITLE
[CUSA26005]: STORY OF SEASONS: Friends of Mineral Town

### ISSUE THREAD

**Issue by Digote** [SysRay/psOff_compatibility#171]
### Please, describe what you get

Nothing.

Critical Error:Missing Symbol| Name:ZiDCxUUGbec#e#e Lib:libSceCes(ver:1) Mod:libSceCes(major:1 minor:1)
Exiting
saving config files
shutting down VideoOut
deinit Graphics| closed: command buffer watcher
deinit Graphics| done
deinit Graphics| closing command processors
-> destruct CommandProcessor[0]
<- destruct CommandProcessor[0]
deinit Graphics| done
deinit Graphics| closing manager
-> deinit ShaderManager
<- deinit ShaderManager
-> deinit SamplerManager
<- deinit SamplerManager
-> deinit PipelineManager
<- deinit PipelineManager
-> deinit GpuMemoryManager
<- deinit GpuMemoryManager
deinit Graphics| done
deinit ImageHandler
deinit ImageHandler| done
VideoOut| Destroy vulkan
Critical Error:Access violation: Execute at addr:0x00000000 info:0x00000000 , module base:0x00000000
Exiting

### Game version you are using

1.0

### Current game status

Nothing

### Your renderer version

v0.5-preview-0

### Your psOff version

https://github.com/SysRay/psOff_public/actions/runs/8949087958

### Upload your log there

[20240504-063229.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/15209206/20240504-063229.000.p7d.zip)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by Digote** [comment]
It seems like it needs more symbols.

Selected GPU:NVIDIA GeForce RTX 4060 Ti api:1.3.277
Error:todo sceCesUcsProfileInitSJis1997Cp932
Critical Error:Missing Symbol| Name:538bRGc6Zo8#e#e Lib:libSceCes(ver:1) Mod:libSceCes(major:1 minor:1)
Exiting
saving config files
shutting down VideoOut
deinit Graphics| closed: command buffer watcher
deinit Graphics| done
deinit Graphics| closing command processors
-> destruct CommandProcessor[0]
<- destruct CommandProcessor[0]
deinit Graphics| done
deinit Graphics| closing manager
-> deinit ShaderManager
<- deinit ShaderManager
-> deinit SamplerManager
<- deinit SamplerManager
-> deinit PipelineManager
<- deinit PipelineManager
-> deinit GpuMemoryManager
<- deinit GpuMemoryManager
deinit Graphics| done
deinit ImageHandler
Error:0x7ff804862e43 base:0x7ff804860000 C:\Program Files (x86)\RivaTuner Statistics Server\Vulkan\RTSSVkLayer64.dll
        GetBootstrapData
Error:offset:0x000025cf  base:0x7ff804860000    C:\Program Files (x86)\RivaTuner Statistics Server\Vulkan\RTSSVkLayer64.dll
Error:0x7fffeef65c4e base:0x7fffeef00000 D:\Emuladores\PS4\psOFF2\core.dll
        ImageHandler::deinit (D:\a\psOff_public\psOff_public\core\videoout\imageHandler.cpp:356:0)
Error:0x7fffeef5d277 base:0x7fffeef00000 D:\Emuladores\PS4\psOFF2\core.dll
        VideoOut::~VideoOut (D:\a\psOff_public\psOff_public\core\videoout\videoout.cpp:381:0)
Critical Error:Access violation: Read at addr:0x7ff804862e43 info:0x00000019 , module base:0x7ff804860000 C:\Program Files (x86)\RivaTuner Statistics Server\Vulkan\RTSSVkLayer64.dll
Exiting

-----------------------------------------------------------------------------------------------------------------------------------------
[20240517-155338.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/15355827/20240517-155338.000.p7d.zip)

**Comment by Digote** [comment]
When I put the update 1.0.1

Selected GPU:NVIDIA GeForce RTX 4060 Ti api:1.3.277
Console:Warning: numAuxBusses is not 0. But this value is ignored
Error:todo sceNgs2SystemCreateWithAllocator(000000002B4DF500, 0000000010C1ACE8, 0000000020C8EE40)
Error:todo sceSaveDataGetParam
Error:todo handle attributes
Console:sceNgs2RackGetVoiceHandle(Main Restricted) is failed | iResult(0x804a0302)
Console:SndStream Version 7.27.12.0 Built on Sep 14 2020 at 06:23:46
Error:todo sceSaveDataGetParam
Error:todo sceSaveDataGetParam
Error:todo sceSaveDataGetParam
Error:todo sceSaveDataGetParam
Error:todo sceSaveDataGetParam
Error:todo sceSaveDataGetParam
Error:todo sceSaveDataGetParam
Error:todo sceSaveDataGetParam
Error:todo sceSaveDataGetParam
Error:todo sceSystemServiceHideSplashScreen
Error:offset:0x002de5e9  base:0x10000000        eboot.bin
Critical Error:Access violation: Read at addr:0x102de5e9 info:0x00000000 , module base:0x10000000 eboot.bin
Exiting
saving config files
shutting down VideoOut
deinit Graphics| closed: command buffer watcher
deinit Graphics| done
deinit Graphics| closing command processors
-> destruct CommandProcessor[0]
<- destruct CommandProcessor[0]
deinit Graphics| done
deinit Graphics| closing manager
-> deinit ShaderManager
<- deinit ShaderManager
-> deinit SamplerManager
<- deinit SamplerManager
-> deinit PipelineManager
<- deinit PipelineManager
-> deinit GpuMemoryManager
<- deinit GpuMemoryManager
deinit Graphics| done
deinit ImageHandler
Error:0x7ff820be2e43 base:0x7ff820be0000 C:\Program Files (x86)\RivaTuner Statistics Server\Vulkan\RTSSVkLayer64.dll
        GetBootstrapData
Error:offset:0x000025cf  base:0x7ff820be0000    C:\Program Files (x86)\RivaTuner Statistics Server\Vulkan\RTSSVkLayer64.dll
Error:0x7fffe7a35c4e base:0x7fffe79d0000 D:\Emuladores\PS4\psOFF2\core.dll
        ImageHandler::deinit (D:\a\psOff_public\psOff_public\core\videoout\imageHandler.cpp:356:0)
Error:0x7fffe7a2d277 base:0x7fffe79d0000 D:\Emuladores\PS4\psOFF2\core.dll
        VideoOut::~VideoOut (D:\a\psOff_public\psOff_public\core\videoout\videoout.cpp:381:0)
Critical Error:Access violation: Read at addr:0x7ff820be2e43 info:0x00000019 , module base:0x7ff820be0000 C:\Program Files (x86)\RivaTuner Statistics Server\Vulkan\RTSSVkLayer64.dll
Exiting

__________________________________________________________________________________________________________________________________

[20240517-160034.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/15356084/20240517-160034.000.p7d.zip)

**Comment by Digote** [comment]
Update.

**Status:**

This screen appears and then crashes.

------------------------------------------------------------------------------------------------------------------------------------

Optimize failed
Couldn't generate shader: fs_0x8d23e6ad
saving config files
shutting down VideoOut
deinit Graphics| closed: command buffer watcher
deinit Graphics| done
deinit Graphics| closing command processors
-> destruct CommandProcessor[0]
<- destruct CommandProcessor[0]
deinit Graphics| done
deinit Graphics| closing manager
-> deinit ShaderManager
ERROR:             vkDestroyDescriptorSetLayout: Invalid device [VUID-vkDestroyDescriptorSetLayout-device-parameter]

----------------------------------------------------------------------------------------------------------------------------------

**Screen**

![01](https://github.com/SysRay/psOff_compatibility/assets/45742711/c17d34be-dbc4-4398-99cd-c7f495edd5da)

**log**

[20240615-032818.000.p7d.zip](https://github.com/user-attachments/files/15845958/20240615-032818.000.p7d.zip)

**Comment by igor725** [comment]
Could you please add lines above `Optimize failed` too?

**Comment by Digote** [comment]
I removed some lines that were repeated a lot.

---------------------------------------------------------------------------------------------------------------------------


D:\Emuladores\PS4\psOFF2>D:\Emuladores\PS4\psOFF2\psoff.exe --file="D:\Emuladores\PS4\PKG\CUSA26005\eboot.bin"
Config graphics.json loaded successfully
Config logging.json loaded successfully
Config audio.json loaded successfully
Config controls.json loaded successfully
Config general.json loaded successfully
Config resolve.json loaded successfully
Renderer version: v.0.6-nightly_08.06.2024
[3] eboot.bin| Image allocation, addr:0x10000000 size:0x10c95030
[4] libc.prx| Image allocation, addr:0x20ca0000 size:0x00121030
[5] libSceFios2.prx| Image allocation, addr:0x30dd0000 size:0x00191030
[6] libSceNpToolkit2.prx| Image allocation, addr:0x20dd0000 size:0x000bd030
Console:------------ Start --------------
Selected GPU:NVIDIA GeForce RTX 4060 Ti api:1.3.278
libSceCes| Error:todo sceCesUcsProfileInitSJis1997Cp932
libSceCes| Error:todo sceCesMbcsUcsContextInit
Console:Warning: numAuxBusses is not 0. But this value is ignored
libSceSaveData| Error:todo sceSaveDataGetParam
libSceAudioOut| Error:todo handle attributes
Console:SCREAM Version 7.27.12.0 Built on Sep 14 2020 at 06:23:46
Console:SndStream Version 7.27.12.0 Built on Sep 14 2020 at 06:23:46
libSceSaveData| Error:todo sceSaveDataGetParam
libSceSystemService| Error:todo sceSystemServiceHideSplashScreen
Console:sceNgs2SamplerVoiceAddWaveformBlocks is failed | iResult(-2142632952)
libSceAppContent| Error:todo sceAppContentGetAddcontInfoList
libSceAppContent| Error:todo sceAppContentGetAddcontInfoList
libSceNpTrophy| Error:Failed to parse trophy data: Invalid trophy key, decrypting is impossible
Console:sceNgs2SamplerVoiceAddWaveformBlocks is failed | iResult(-2142632952)
libSceNpTrophy| Error:Failed to parse trophy data: Invalid trophy key, decrypting is impossible
detile tilingIdx unknown 0
(fs_0x8d23e6ad) Compile error, line:0 column:0 | (ID '230[%230]' has not been defined
  %240 = OpBitcast %float %230
)
Optimize failed
Couldn't generate shader: fs_0x8d23e6ad
saving config files
shutting down VideoOut
deinit Graphics| closed: command buffer watcher
deinit Graphics| done
deinit Graphics| closing command processors
-> destruct CommandProcessor[0]
<- destruct CommandProcessor[0]
deinit Graphics| done
deinit Graphics| closing manager
-> deinit ShaderManager
ERROR:             vkDestroyDescriptorSetLayout: Invalid device [VUID-vkDestroyDescriptorSetLayout-device-parameter]

D:\Emuladores\PS4\psOFF2>
