### ISSUE TITLE
[CUSA13959]: Forager

### ISSUE THREAD

**Issue by Hermiten** [SysRay/psOff_compatibility#193]
### Please, describe what you get

Playable but after sometimes it crash

### Game version you are using

01.00

### Current game status

Ingame

### Your renderer version

v.0.5-nightly_04.05.24

### Your psOff version

0e4c31a17cf401393e46c8bebf93c8e09438ce7a

### Upload your log there

[20240505-223024.000.zip](https://github.com/SysRay/psOff_compatibility/files/15214462/20240505-223024.000.zip)

### Upload your screenshots there

<img width="940" alt="image" src="https://github.com/SysRay/psOff_compatibility/assets/151466/2e7fe001-26f5-499a-819d-ce9de31c791e">

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by igor725** [comment]
Please post the console output and log file after the crash
