### ISSUE TITLE
[CUSA00222]: EA Sports UFC

### ISSUE THREAD

**Issue by Digote** [SysRay/psOff_compatibility#21]
### Please, describe what you get

Running this game results in an **unknown exception**.

Error:Exception 0x7ffb693353ac
Error:0x14001fd27
Error:0x14001bab7
Error:0x140016347
Error:0x14005fd49
Error:0x7ffb6bf3440f
Error:0x7ffb6beae466
Error:0x7ffb6bee4465
Error:0x7ffb693353ac
Error:0x7ffb5b086ba7
Error:0x7ffb437059ef
Error:0x7ffb43701f81
Error:0x10d723f7          in eboot.bin
Error:unknown exception: 0x7ffb693353ac

### Game version you are using

1.0.8

### Current game status

Nothing

### Your emulator version

v0.5-preview-0

### psOff-libs version you are using

https://github.com/SysRay/psOff_public/actions/runs/8680801463

### Upload your log there

[20240414-215032.000.zip](https://github.com/SysRay/psOff_compatibility/files/14972825/20240414-215032.000.zip)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by GAMERRPCS3** [comment]
Retest 

the game remains blocked and the FPS display etc. and freeze.

![Capture d’écran 2024-04-19 142800](https://github.com/SysRay/psOff_compatibility/assets/121258975/eb7615e6-48e0-4d2b-b6d8-5f6c28855482)
