### ISSUE TITLE
[CUSA01009]: The Wolf Among Us

### ISSUE THREAD

**Issue by Digote** [SysRay/psOff_compatibility#212]
### Please, describe what you get

Nothing.

Error:todo sceSystemServiceHideSplashScreen
Error:todo constBuffer
Error:todo sceNpSetContentRestriction
Error:todo constBuffer
Error:offset:0x00004c59  base:0x10000000        eboot.bin
Critical Error:Access violation: Read at addr:0x10004c59 info:0x00000000 , module base:0x10000000 eboot.bin
Exiting

### Game version you are using

1.0

### Current game status

Nothing

### Your renderer version

v0.5-preview-0

### Your psOff version

https://github.com/SysRay/psOff_public/actions/runs/9029751981

### Upload your log there

[20240511-070722.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/15282415/20240511-070722.000.p7d.zip)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by igor725** [comment]
Duplicate #158
