### ISSUE TITLE
[CUSA00540]: Tiny Troopers Joint Ops

### ISSUE THREAD

**Issue by Digote** [SysRay/psOff_compatibility#213]
### Please, describe what you get

Nothing.

Error:todo sceKernelGetModuleInfo(1)
Error:todo sceKernelGetModuleInfo(2)
Error:todo sceKernelGetModuleInfo(3)
Error:todo sceKernelGetModuleInfo(4)
Error:todo sceKernelGetModuleInfo(5)
Error:todo sceKernelGetModuleInfo(6)
Error:todo sceKernelGetModuleInfo(7)
Error:todo sceKernelGetModuleInfo(8)
Error:0x00000012
Critical Error:Access violation: Execute at addr:0x00000012 info:0x00000012 , module base:0x00000000
Exiting
saving config files
shutting down VideoOut
deinit Graphics| closed: command buffer watcher
deinit Graphics| done
deinit Graphics| closing command processors
-> destruct CommandProcessor[0]
<- destruct CommandProcessor[0]
deinit Graphics| done
deinit Graphics| closing manager
-> deinit ShaderManager
<- deinit ShaderManager
-> deinit SamplerManager
<- deinit SamplerManager
-> deinit PipelineManager
<- deinit PipelineManager
-> deinit GpuMemoryManager
<- deinit GpuMemoryManager
deinit Graphics| done
deinit ImageHandler
Error:0x7ffd6d252e43 base:0x7ffd6d250000 C:\Program Files (x86)\RivaTuner Statistics Server\Vulkan\RTSSVkLayer64.dll
        GetBootstrapData
Error:offset:0x000025cf  base:0x7ffd6d250000    C:\Program Files (x86)\RivaTuner Statistics Server\Vulkan\RTSSVkLayer64.dll
Error:0x7ffd4943689e base:0x7ffd493d0000 D:\Emuladores\PS4\psOff\core.dll
        ImageHandler::deinit (D:\a\psOff_public\psOff_public\core\videoout\imageHandler.cpp:356:0)
Error:0x7ffd4942df97 base:0x7ffd493d0000 D:\Emuladores\PS4\psOff\core.dll
        VideoOut::~VideoOut (D:\a\psOff_public\psOff_public\core\videoout\videoout.cpp:381:0)
Critical Error:Access violation: Read at addr:0x7ffd6d252e43 info:0x00000019 , module base:0x7ffd6d250000 C:\Program Files (x86)\RivaTuner Statistics Server\Vulkan\RTSSVkLayer64.dll
Exiting

### Game version you are using

1.0

### Current game status

Nothing

### Your renderer version

v0.5-preview-0

### Your psOff version

https://github.com/SysRay/psOff_public/actions/runs/9029751981

### Upload your log there

[20240511-070947.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/15282422/20240511-070947.000.p7d.zip)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by yaya54840** [comment]
with the latest emulator
we are in game with graphics bug on the character
![Capture d'écran 2024-06-11 142002](https://github.com/SysRay/psOff_compatibility/assets/47884186/04120fc0-7ff7-4118-b54d-491ea1968a90)
![Capture d'écran 2024-06-10 224643](https://github.com/SysRay/psOff_compatibility/assets/47884186/b65cee7e-4642-45d8-afaf-149dbb9fc6ac)

[20240611-141836.000.p7d.zip](https://github.com/user-attachments/files/15787879/20240611-141836.000.p7d.zip)

**Comment by yaya54840** [comment]
![Capture d'écran 2024-06-15 094849](https://github.com/SysRay/psOff_compatibility/assets/47884186/e150f9e6-de5f-40fa-a79e-b26c52f3b8be)
