### ISSUE TITLE
[CUSA39324]: Marsi's Adventures

### ISSUE THREAD

**Issue by yaya54840** [SysRay/psOff_compatibility#222]
### Please, describe what you get

Perfect emulation
Playable for me

### Game version you are using

v1.00

### Current game status

Nothing

### Your renderer version

v.0.5-Nightly_04.05.24

### Upload your log there

[log.txt](https://github.com/SysRay/psOff_compatibility/files/15283321/log.txt)

### Upload your screenshots there

![Capture d'écran 2024-05-11 173123](https://github.com/SysRay/psOff_compatibility/assets/47884186/dcb09558-61e8-4548-a68b-6c040e4d3d49)
![Capture d'écran 2024-05-11 173147](https://github.com/SysRay/psOff_compatibility/assets/47884186/b7f9736b-e0a7-4ba7-a275-de446cd65deb)
![Capture d'écran 2024-05-11 173214](https://github.com/SysRay/psOff_compatibility/assets/47884186/da2919af-c814-42a0-8653-34d92faca14d)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by igor725** [comment]
Already posted #167
