### ISSUE TITLE
[CUSA23518]: Aleste Collection

### ISSUE THREAD

**Issue by yaya54840** [SysRay/psOff_compatibility#234]
### Please, describe what you get

Good morning
The game starts but we get stuck on this screen
Igor I put boot or intro ?

### Game version you are using

v1.00

### Current game status

Intro

### Your renderer version

v.0.5-nightly_04.05.24

### Upload your log there

[log.txt](https://github.com/SysRay/psOff_compatibility/files/15285539/log.txt)

### Upload your screenshots there

![Capture d'écran 2024-05-12 101056](https://github.com/SysRay/psOff_compatibility/assets/47884186/d62693eb-96ff-47e4-b517-39a07f787e78)
![Capture d'écran 2024-05-12 101330](https://github.com/SysRay/psOff_compatibility/assets/47884186/44068802-bb9e-4b1a-b5a7-5de715842576)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by igor725** [comment]
Please post the game's log from P7Logs folder

**Comment by yaya54840** [comment]
Ah ok but what software do you open them with?

[20240512-161734.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/15286581/20240512-161734.000.p7d.zip)

**Comment by igor725** [comment]
> Ah ok but what software do you open them with?
> 
> [20240512-161734.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/15286581/20240512-161734.000.p7d.zip)

https://baical.net/downloads.html
You need Baical Server x64

**Comment by yaya54840** [comment]
THANKS
I can open them now
but it's too complicated for me, I don't have the level.
Congratulations for what you do.

**Comment by yaya54840** [comment]
![Capture d'écran 2024-06-21 150217](https://github.com/SysRay/psOff_compatibility/assets/47884186/192edf13-4905-4a44-94c7-6a85960cd300)

Igor we are in play now
