### ISSUE TITLE
[CUSA28803]: Arietta of Spirits

### ISSUE THREAD

**Issue by yaya54840** [SysRay/psOff_compatibility#237]
### Please, describe what you get

The game starts and you can play it
But there is a bug in the game
Which prevents us from going further

### Game version you are using

1.02

### Current game status

Ingame

### Your renderer version

v.0.5-nightly_04.05.24

### Upload your log there

Igor
The log is too big
Even compressed

### Upload your screenshots there

![Capture d'écran 2024-05-14 084557](https://github.com/SysRay/psOff_compatibility/assets/47884186/b1cf1595-49b3-4e9d-9098-9df71a4bceae)
![Capture d'écran 2024-05-14 084620](https://github.com/SysRay/psOff_compatibility/assets/47884186/3db00d84-88c5-4d4d-9a1a-ceeb37c7ec66)
![Capture d'écran 2024-05-14 084704](https://github.com/SysRay/psOff_compatibility/assets/47884186/c18b8b32-9689-4267-be72-b71f1f5dd7dd)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by GamingDucking** [comment]
I would suggest files.fm (if you still have the zip file).

**Comment by yaya54840** [comment]
files.fm I don't see where.
maybe when the game is open.

**Comment by GamingDucking** [comment]
> files.fm I don't see where. maybe when the game is open.
> 
> ok it's good you don't have to wait too much in the game otherwise the p7d is very big
> 
> [log.zip](https://github.com/SysRay/psOff_compatibility/files/15316817/log.zip)

I meant the website.

**Comment by SysRay** [comment]
Changing the following two values in config/logging.json should reduce the log size.
"Render": 3
"GpuMemoryManager": 3

**Comment by SysRay** [comment]
Could you add the command window output aswell, please?

**Comment by yaya54840** [comment]
[log.txt](https://github.com/SysRay/psOff_compatibility/files/15321731/log.txt)

**Comment by igor725** [comment]
Well, I don't see any obvious errors there, weird

**Comment by yaya54840** [comment]
Hi igor725
I think it comes from the game itself.
I will retest with version 1.00

**Comment by igor725** [comment]
> Hi igor725 I think it comes from the game itself. I will retest with version 1.00
> 
> It does the same in v1.00 It comes from the game I think. In any case since you integrated (Merge pull request #158 from igor725/vbuf) I have a lot of games that work. Thank you for your work.

This pullrequest does not affect any game actually. So all games will keep their current status.
