### ISSUE TITLE
[CUSA26608]: Bloodrayne Betrayal: Fresh Bytes

### ISSUE THREAD

**Issue by yaya54840** [SysRay/psOff_compatibility#238]
### Please, describe what you get

In-game with v.0.5-nightly_27.05.24

### Game version you are using

v1.01

### Current game status

Ingame

### Your renderer version

v.0.5-nightly_27.05.24

### Upload your log there

[20240528-090442.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/15465300/20240528-090442.000.p7d.zip)

### Upload your screenshots there

![Capture d'écran 2024-05-14 090655](https://github.com/SysRay/psOff_compatibility/assets/47884186/0a62128b-2763-4b12-a20a-35ad690cd26a)
![Capture d'écran 2024-05-14 090730](https://github.com/SysRay/psOff_compatibility/assets/47884186/6f586e75-79af-470c-9d63-d89b82201943)
![Capture d'écran 2024-05-28 090550](https://github.com/SysRay/psOff_compatibility/assets/47884186/15025042-9ec5-441d-9bb2-1617a79ee7ff)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by SysRay** [comment]
Could you add the command window output please?  Only the end where the shader generation fails.

**Comment by yaya54840** [comment]
Hi igor I edited
Because this game works now
