### ISSUE TITLE
[CUSA19069]: NAMCO MUSEUM  ARCHIVES Vol 1

### ISSUE THREAD

**Issue by yaya54840** [SysRay/psOff_compatibility#245]
### Please, describe what you get

The game starts up to the menu
and return to office

### Game version you are using

v1.00

### Current game status

Ingame

### Your renderer version

v.0.5-nightly_04.05.24

### Upload your log there

[log.zip](https://github.com/SysRay/psOff_compatibility/files/15332022/log.zip)

### Upload your screenshots there

![Capture d'écran 2024-05-16 103055](https://github.com/SysRay/psOff_compatibility/assets/47884186/cf093971-7c10-446a-bdbe-8c3a0a9dcb2d)
![Capture d'écran 2024-05-16 103107](https://github.com/SysRay/psOff_compatibility/assets/47884186/56ea90e4-b6d2-4ca7-a8a1-9b5b639aece2)
![Capture d'écran 2024-05-16 103137](https://github.com/SysRay/psOff_compatibility/assets/47884186/17cf1439-4ad6-438b-b2ab-3ef6fd354b8d)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by ArbestRi02** [comment]
Trying to play a game gives this infinitely
![image](https://github.com/SysRay/psOff_compatibility/assets/168323856/22432edc-e002-4c3c-aeb3-84d60886eba2)
