### ISSUE TITLE
[CUSA03082]: Trine 3: The Artifacts of Power

### ISSUE THREAD

**Issue by GAMERRPCS3** [SysRay/psOff_compatibility#25]
### Please, describe what you get

The game crashes after loading.

### Game version you are using

01.00

### Current game status

Intro

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

3467b160e7929caf7b3b956f870c2cbef47cf107

### Upload your log there

[20240415-064629.000.zip](https://github.com/SysRay/psOff_compatibility/files/14974074/20240415-064629.000.zip)

### Upload your screenshots there

![Capture d’écran 2024-04-15 064255](https://github.com/SysRay/psOff_compatibility/assets/121258975/823a5417-47ad-47cb-a01f-457bf9733016)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by yaya54840** [comment]
In game now but only shows subtitles
![Capture d'écran 2024-05-29 114124](https://github.com/SysRay/psOff_compatibility/assets/47884186/8d17b79c-1f6f-490f-9d5c-f273318160a7)

the audio is there

[20240529-114345.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/15482392/20240529-114345.000.p7d.zip)
