### ISSUE TITLE
[CUSA04241]: Risk of Rain

### ISSUE THREAD

**Issue by Hermiten** [SysRay/psOff_compatibility#26]
### Please, describe what you get

Console:  sceKernelStat : 0x80020002(/savedata0/save.csv)
Error:0x14001fd27
Error:0x14001bab7
Error:0x140014353
Error:0x00691538
Critical Error:Missing Symbol| Name:XOzszO4ONWU#X#W Lib:libSceNpTus(ver:1) Mod:libSceNpTus(major:1 minor:1)
Exiting

### Game version you are using

01.00

### Current game status

Intro

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

3467b160e7929caf7b3b956f870c2cbef47cf107

### Upload your log there

https://filebin.net/sjtoff10qmdm84au/20240415-125131.000.p7d

### Upload your screenshots there

![image](https://github.com/SysRay/psOff_compatibility/assets/151466/a423e422-ecfe-428a-b815-66d7ffec61d1)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by igor725** [comment]
Retest with https://github.com/SysRay/psOff_public/actions/runs/8688184966

**Comment by Hermiten** [comment]
> Retest with https://github.com/SysRay/psOff_public/actions/runs/8688184966

Better, I can go further but then:

Critical Error:Missing Symbol| Name:ekGJmmoc8j4#p#k Lib:libSceNgs2(ver:1) Mod:libSceNgs2(major:1 minor:1)

**Comment by GAMERRPCS3** [comment]
> Retest with https://github.com/SysRay/psOff_public/actions/runs/8688184966

I just tested it and it works perfectly. I add the libSceNgs2.prx module to it.

**Comment by igor725** [comment]
> > Retest with https://github.com/SysRay/psOff_public/actions/runs/8688184966
> 
> I just tested it and it works perfectly. I add the libSceNgs2.prx module to it.

Compatibility tests should be performed without any changes to game's directory and modules. If you made these changes you should mention them.

**Comment by Hermiten** [comment]
Now it's playable ! 

![image](https://github.com/SysRay/psOff_compatibility/assets/151466/6156af77-29f0-402f-9f58-f69796e09429)

Log:
[20240416-195013.000.zip](https://github.com/SysRay/psOff_compatibility/files/15000876/20240416-195013.000.zip)

Version:
https://github.com/SysRay/psOff_public/actions/runs/8708816790

**Comment by gandalfthewhite19890404** [comment]
Resolved symbols - sceNpTusGetData , sceNgs2GetWaveformFrameInfo
