### ISSUE TITLE
[CUSA20201]: Turok

### ISSUE THREAD

**Issue by igor725** [SysRay/psOff_compatibility#268]
### Please, describe what you get

The game crashes inside `avplayer.cpp` trying to decode the audiodata. `m_audio.frame` is `nullptr` at the moment of crash, so this is probably a race condition. If I set breakpoint there and immediately resume the game then audio playing for a moment, but then the game crashes again with `Critical Error:Couldn't vkQueueSubmit Transfer VK_ERROR_DEVICE_LOST`.

### Game version you are using

v01.00

### Current game status

Nothing

### Your renderer version

v.0.5-nightly_04.05.24

### Your psOff version

6d58b63d476439a018c980a0ed940644434162d1

### Upload your log there

No audio breakpoint:
[20240527-083023.000.zip](https://github.com/SysRay/psOff_compatibility/files/15451311/20240527-083023.000.zip)

Audio breakpoint:
[20240527-083504.000.zip](https://github.com/SysRay/psOff_compatibility/files/15451337/20240527-083504.000.zip)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by yaya54840** [comment]
with the latest emulator
![Capture d'écran 2024-06-11 142717](https://github.com/SysRay/psOff_compatibility/assets/47884186/fbd3bb42-ab26-48a9-b22c-a680654c3006)
![Capture d'écran 2024-06-11 142735](https://github.com/SysRay/psOff_compatibility/assets/47884186/9e9eafbf-3d74-4aab-a67b-03996f8e4999)

we are in game with graphics bug

[20240611-142643.000.p7d.zip](https://github.com/user-attachments/files/15787916/20240611-142643.000.p7d.zip)
