### ISSUE TITLE
[CUSA02906]: The Treasures of Montezuma 4

### ISSUE THREAD

**Issue by Hermiten** [SysRay/psOff_compatibility#27]
### Please, describe what you get

Stuck on black screen

Error:todo sceNgs2SystemCreateWithAllocator(0000000000000000, 00000000027CCAA0, 00000000027CCA60)
Error:todo sceNgs2SystemCreateWithAllocator(0000000000000000, 00000000027CCAA0, 00000000027CCA98)
Error:todo sceNpSetContentRestriction
Error:todo sceNpRegisterStateCallback
Error:todo sceSystemServiceHideSplashScreen
Error:todo sceNgs2ParseWaveformFile
Error:ParseRIFF: ffmpeg failed to read passed data: -1094995529
Error:todo sceSaveDataUmountWithBackup
Error:todo sceNgs2ParseWaveformFile
Error:ParseRIFF: ffmpeg failed to read passed data: -1094995529
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000000010f17cc0] stream 0, timescale not set
Error:openCodecContext: no audio stream
Error:todo sceSystemServiceDisableMusicPlayer
Error:munmap unkown 0x2ea20000 0x00100000
Error:todo Release
Error:munmap unkown 0x2eb20000 0x00100000
Error:todo Release

### Game version you are using

01.00

### Current game status

Nothing

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

3467b160e7929caf7b3b956f870c2cbef47cf107

### Upload your log there

Too big, 300Mo

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by Hermiten** [comment]
Here the log:
[20240505-213056.000.zip](https://github.com/SysRay/psOff_compatibility/files/15214227/20240505-213056.000.zip)

Emulator version:
https://github.com/SysRay/psOff_public/actions/runs/8959234568

**Comment by yaya54840** [comment]
the game starts with the latest emu v.0.5-nightly_27.05.24
![Capture d'écran 2024-06-02 103521](https://github.com/SysRay/psOff_compatibility/assets/47884186/93325dcc-c0e6-4563-a80f-6f6767b24ab8)
![Capture d'écran 2024-06-02 103548](https://github.com/SysRay/psOff_compatibility/assets/47884186/08674a78-5e93-4bbf-b294-976886ad19df)

but black screen when you want to go further than the menu

[20240602-103511.000.p7d.zip](https://github.com/user-attachments/files/15524695/20240602-103511.000.p7d.zip)
