### ISSUE TITLE
[CUSA14370]: Ghost of a Tale

### ISSUE THREAD

**Issue by GAMERRPCS3** [SysRay/psOff_compatibility#270]
### Please, describe what you get

Nothing - Missing Symbol

Console:Argument Count = 1Arg 0 = psOff
Console:********** LAUNCHER CONTROL ************************************
Console:        File System Root = NONE SPECIFIED
Console:        Launcher Path = NONE SPECIFIED
Console:        Launcher Arguments NONE SPECIFIED
Console:**********/LAUNCHER CONTROL ************************************
[6] PS4Util.prx| Image allocation, addr:0x18cd0000 size:0x00405030
[7] Il2CppUserAssemblies.prx| Image allocation, addr:0x1afb0000 size:0x01d3d030
Console:MouseInit
Error:todo constBuffer
[17] UnityNpToolkit2.prx| Image allocation, addr:0x3e7c0000 size:0x00405030
Error:todo __sce__ZN3sce7Toolkit2NP2V24Core7Request10InitParamsC1Ev
Error:todo __sce__ZN3sce7Toolkit2NP2V24Core4initERKNS3_7Request10InitParamsE
Error:todo __sce__ZN3sce7Toolkit2NP2V24Core7Request10InitParamsD1Ev
Error:todo __sce__ZN3sce7Toolkit2NP2V24Core8ResponseINS3_5EmptyEEC1Ev
Error:todo __sce__ZN3sce7Toolkit2NP2V26Trophy7Request18RegisterTrophyPackC1Ev
Error:todo __sce__ZN3sce7Toolkit2NP2V26Trophy18registerTrophyPackERKNS3_7Request18RegisterTrophyPackEPNS2_4Core8ResponseINS8_5EmptyEEE
Critical Error:Missing Symbol| Name:El4tFb9f8dk#M#N Lib:libSceNpToolkit2(ver:1) Mod:libSceNpToolkit2(major:0 minor:0)
Exiting
saving config files
shutting down VideoOut
deinit Graphics| closed: command buffer watcher
deinit Graphics| done
deinit Graphics| closing command processors
-> destruct CommandProcessor[0]
<- destruct CommandProcessor[0]
deinit Graphics| done
deinit Graphics| closing manager
-> deinit ShaderManager
<- deinit ShaderManager
-> deinit SamplerManager
<- deinit SamplerManager
-> deinit PipelineManager
<- deinit PipelineManager
-> deinit GpuMemoryManager
Error:0x7ff80baa2f32 base:0x7ff80ac40000 C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_5cf411dadcb5710d\nvoglv64.dll
        vkGetInstanceProcAddr
Error:0x7ff80baa0c8f base:0x7ff80ac40000 C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_5cf411dadcb5710d\nvoglv64.dll
        vkGetInstanceProcAddr
Error:0x7ff81ee20b85 base:0x7ff81edd0000 F:\psOff-artifact\psoff_render.dll
        GpuMemoryManager::deinit
Error:0x7ff81ee39dc6 base:0x7ff81edd0000 F:\psOff-artifact\psoff_render.dll
        Manager::deinit
Critical Error:Access violation: Read at addr:0x7ff80baa2f32 info:0x1000003d0 , module base:0x7ff80ac40000 C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_5cf411dadcb5710d\nvoglv64.dll
Exiting

### Game version you are using

01.00

### Current game status

Nothing

### Your renderer version

v.0.5-nightly_27.05.24

### Your psOff version

dba704438a6260ae55e8815e9535d99a98b248c4

### Upload your log there

[5wm6daj4knyw1nzs.zip](https://github.com/SysRay/psOff_compatibility/files/15459237/5wm6daj4knyw1nzs.zip)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by igor725** [comment]
Probably will progress further with SysRay/psOff_public#170

**Comment by GAMERRPCS3** [comment]
Retest 

now the game starts without problem with the introduction. then crash while loading.



Console:Argument Count = 1Arg 0 = psOff
Console:********** LAUNCHER CONTROL ************************************
Console:        File System Root = NONE SPECIFIED
Console:        Launcher Path = NONE SPECIFIED
Console:        Launcher Arguments NONE SPECIFIED
Console:**********/LAUNCHER CONTROL ************************************
[6] PS4Util.prx| Image allocation, addr:0x18e60000 size:0x00405030
[7] Il2CppUserAssemblies.prx| Image allocation, addr:0x1b140000 size:0x01d3d030
Console:MouseInit
Error:todo constBuffer
[17] UnityNpToolkit2.prx| Image allocation, addr:0x3e6e0000 size:0x00405030
Error:todo __sce__ZN3sce7Toolkit2NP2V24Core7Request10InitParamsC1Ev
Error:todo __sce__ZN3sce7Toolkit2NP2V24Core4initERKNS3_7Request10InitParamsE
Error:todo __sce__ZN3sce7Toolkit2NP2V24Core7Request10InitParamsD1Ev
Error:todo __sce__ZN3sce7Toolkit2NP2V24Core8ResponseINS3_5EmptyEEC1Ev
Error:todo __sce__ZN3sce7Toolkit2NP2V26Trophy7Request18RegisterTrophyPackC1Ev
Error:todo __sce__ZN3sce7Toolkit2NP2V26Trophy18registerTrophyPackERKNS3_7Request18RegisterTrophyPackEPNS2_4Core8ResponseINS8_5EmptyEEE
Error:todo __sce__ZNK3sce7Toolkit2NP2V24Core11RequestBase15getFunctionTypeEv
Error:todo __sce__ZN3sce7Toolkit2NP2V26Trophy7Request18RegisterTrophyPackD1Ev
Error:todo sceSystemServiceHideSplashScreen
Error:todo sceNpGetAccountIdA
Error:Unknown controller backend "gamepad" falling back to "SDL"
Error:offset:0x012d152b  base:0x1b140000        Il2CppUserAssemblies.prx
Critical Error:Access violation: Read at addr:0x1c41152b info:0x001e13d8 , module base:0x1b140000 Il2CppUserAssemblies.prx
Exiting
saving config files
shutting down VideoOut
deinit Graphics| closed: command buffer watcher
deinit Graphics| done
deinit Graphics| closing command processors
-> destruct CommandProcessor[0]
<- destruct CommandProcessor[0]
deinit Graphics| done
deinit Graphics| closing manager
-> deinit ShaderManager
Error:0x7ff81dd5a959 base:0x7ff81dd00000 C:\Windows\SYSTEM32\vulkan-1.dll
        vkResetEvent
Error:0x7ff81939a05a base:0x7ff819330000 F:\psOff-artifact\psoff_render.dll
        ShaderData::~ShaderData
Error:0x7ff8193b7f40 base:0x7ff819330000 F:\psOff-artifact\psoff_render.dll
        VertexShaderData::~VertexShaderData
Error:0x7ff8193b7e09 base:0x7ff819330000 F:\psOff-artifact\psoff_render.dll
        ShaderData::ShaderData
Critical Error:Access violation: Read at addr:0x7ff81dd5a959 info:0xc00000024 , module base:0x7ff81dd00000 C:\Windows\SYSTEM32\vulkan-1.dll
Exiting

[00i4mfntzwbyqep2.zip](https://github.com/SysRay/psOff_compatibility/files/15461990/00i4mfntzwbyqep2.zip)
