### ISSUE TITLE
[CUSA03328]: Chronicles of Teddy: Harmony of Exidus

### ISSUE THREAD

**Issue by yaya54840** [SysRay/psOff_compatibility#276]
### Please, describe what you get

Stake

### Game version you are using

v1.00

### Current game status

Ingame

### Your renderer version

v.0.6-nightly_27.05.24

### Upload your log there

[20240528-092615.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/15465557/20240528-092615.000.p7d.zip)

### Upload your screenshots there

![Capture d'écran 2024-05-28 092424](https://github.com/SysRay/psOff_compatibility/assets/47884186/92c34fc5-46e4-446a-9418-d76dca4bcaf3)
![Capture d'écran 2024-05-28 092446](https://github.com/SysRay/psOff_compatibility/assets/47884186/e2aed586-03e9-4b1c-962e-acacf67c28aa)
![Capture d'écran 2024-05-28 0
![Capture d'écran 2024-07-24 091755](https://github.com/user-attachments/assets/37e32abd-1c24-4da3-9792-8d82c837fec7)
92658](https://github.com/SysRay/psOff_compatibility/assets/47884186/1b9315ea-de01-4c6c-9354-e47860b440bd)

### Yes, I agree
![Capture d'écran 2024-07-24 091755](https://github.com/user-attachments/assets/092a4842-08e6-4b9f-a9f7-6d7d6b0b71bc)

- [X] Yes, I read the rules and did everything according to them

**Comment by SysRay** [comment]
Missing Symbol| Name:-cTaKlIkf7o#U#V Lib:libScePiglet(ver:1) Mod:libScePiglet(major:1 minor:1)

**Comment by igor725** [comment]
libScePiglet.prx should be shipped with the game itself, your dump is probably broken.

**Comment by yaya54840** [comment]
Hi Igor725
Happy to see you again
Yes I removed the libScePiglet.prx from the CUSA SCE_Module and the game is playable
Nightly_08.06.2024

PS: Everyone would have wanted psOff to continue

**Comment by igor725** [comment]
> Hi Igor725 Happy to see you again Yes I removed the libScePiglet.prx from the CUSA SCE_Module and the game is playable Nightly_08.06.2024
> 
> PS: Everyone would have wanted psOff to continue

We haven't stopped the project. The development is going on in private mode and maybe soon you will see the results. I just scanned through `missing-symbol` reports yesterday to check what functions I missed and saw this report.

**Comment by yaya54840** [comment]
Ah Super
It's reassuring
Looking forward to seeing a next release!
Best wishes !
