### ISSUE TITLE
[CUSA06164]: The Evil Within® 2

### ISSUE THREAD

**Issue by GAMERRPCS3** [SysRay/psOff_compatibility#277]
### Please, describe what you get

Nothing - Missing Symbol

Error:todo sceGameLiveStreamingInitialize
Error:todo sceRemoteplayInitialize
Error:todo sceCoredumpRegisterCoredumpHandler
Critical Error:Missing Symbol| Name:EmpW38vZWAY#Y#Y Lib:libSceNpToolkit2(ver:1) Mod:libSceNpToolkit2(major:0 minor:0)
Exiting
Error:offset:0x00e87b8b  base:0x10000000        eboot.bin
Critical Error:Access violation: Read at addr:0x10e87b8b info:0x00000000 , module base:0x10000000 eboot.bin
Exiting

### Game version you are using

01.00

### Current game status

Nothing

### Your renderer version

v.0.5-nightly_27.05.24

### Your psOff version

f6d15bfea2ed05204d06517c14ce96cc2bd817b8

### Upload your log there

[bfp6txtln0t80e3z.zip](https://github.com/SysRay/psOff_compatibility/files/15472489/bfp6txtln0t80e3z.zip)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by igor725** [comment]
Should progress further with SysRay/psOff_public#170

**Comment by GAMERRPCS3** [comment]
Retest 

Error:todo sceGameLiveStreamingInitialize
Error:todo sceRemoteplayInitialize
Error:todo sceCoredumpRegisterCoredumpHandler
Error:todo __sce__ZN3sce7Toolkit2NP2V24Core8ResponseINS2_3TSS7TssDataEEC1Ev
Error:TODO: scePlayGoSetToDoList
Error:offset:0x0103e4cb  base:0x10000000        eboot.bin
Critical Error:Access violation: Read at addr:0x1103e4cb info:0x00000000 , module base:0x10000000 eboot.bin
Exiting
[y5fzdvqz81wibhtv.zip](https://github.com/SysRay/psOff_compatibility/files/15473791/y5fzdvqz81wibhtv.zip)
