### ISSUE TITLE
[CUSA07965]: 8-Bit Invaders

### ISSUE THREAD

**Issue by Hermiten** [SysRay/psOff_compatibility#28]
### Please, describe what you get

Crash

Missing Symbol| Name:im2ZuItabu4#E#F Lib:libSceGnmDriver(ver:1) Mod:libSceGnmDriver(major:1 minor:1)

### Game version you are using

01.00

### Current game status

Nothing

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

0db00ad69fcd51855096e94651fb06b13b374c5f

### Upload your log there

[20240415-141419.000.zip](https://github.com/SysRay/psOff_compatibility/files/14979393/20240415-141419.000.zip)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by gandalfthewhite19890404** [comment]
Unimplemented - sceGnmDrawInitToDefaultContextState400

**Comment by igor725** [comment]
> Crash: [20240426-233838.000.zip](https://github.com/SysRay/psOff_compatibility/files/15188626/20240426-233838.000.zip)
> 
> Emulator version: https://github.com/SysRay/psOff_public/actions/runs/8923990881

Provide console output too please

**Comment by Hermiten** [comment]
Okay here a new test.
It's seem's to be cause by "sceSaveDataTransferringMount" ?

Console:

> Console:user_malloc_init available memory: 6441402368 of 6442450944, used memory: 4821352448
> Selected GPU:AMD Radeon(TM) 780M api:1.3.246
> Error:todo sceSaveDataTransferringMount
> Error:offset:0x0006543c  base:0x7ff9f3550000    C:\Windows\System32\KERNELBASE.dll
> Error:offset:0x00006ba7  base:0x7ff9c9120000    C:\Windows\SYSTEM32\VCRUNTIME140.dll
> Error:offset:0x00039542  base:0x7ff91e5f0000    C:\Windows\SYSTEM32\MSVCP140.dll
> Error:offset:0x00008210  base:0x7ff9c1aa0000    C:\Users\titou\Desktop\PS4Emu\psOff\modules\libSceSaveData.dll
> Critical Error:unknown exception at 0x7ff9f35b543c, module base:0x7ff9f3550000 C:\Windows\System32\KERNELBASE.dll
> Exiting
> saving config files
> shutting down VideoOut
> deinit Graphics| closed: command buffer watcher
> deinit Graphics| done
> deinit Graphics| closing command processors
> -> destruct CommandProcessor[0]
> <- destruct CommandProcessor[0]
> deinit Graphics| done
> deinit Graphics| closing manager
> -> deinit ShaderManager
> <- deinit ShaderManager
> -> deinit SamplerManager
> <- deinit SamplerManager
> -> deinit PipelineManager
> <- deinit PipelineManager
> -> deinit GpuMemoryManager
> <- deinit GpuMemoryManager
> deinit Graphics| done
> deinit ImageHandler

log:
[20240505-205310.000.zip](https://github.com/SysRay/psOff_compatibility/files/15214130/20240505-205310.000.zip)


Emulator:
https://github.com/SysRay/psOff_public/actions/runs/8959234568

**Comment by igor725** [comment]
The game crashes inside `sceSaveDataUmount` function. For some reason it puts empty `mountPoint` there. We'll check it.
