### ISSUE TITLE
[CUSA00369]: Lords of the Fallen

### ISSUE THREAD

**Issue by GAMERRPCS3** [SysRay/psOff_compatibility#286]
### Please, describe what you get

the game starts, and crashes after the introduction.

Console:Initializing direct memory - 6144 MiB of memory available...
libScePlayGo| Error:TODO: scePlayGoSetInstallSpeed
libSceNpManager| Error:todo sceNpSetNpTitleId
Selected GPU:NVIDIA GeForce RTX 3090 api:1.3.278
libScePad| Error:Unknown controller backend "gamepad" falling back to "SDL"
libSceSystemService| Error:todo sceSystemServiceHideSplashScreen
libSceVideoOut| Error:TODO sceVideoOutSetWindowModeMargins
libSceVideoOut| Error:TODO sceVideoOutSetWindowModeMargins
Couldn't find VGPR(3) for 13(TypeBlock) (items found:1)
libSceVideoOut| Error:TODO sceVideoOutSetWindowModeMargins
libSceVideoOut| Error:TODO sceVideoOutSetWindowModeMargins
libSceVideoOut| Error:TODO sceVideoOutSetWindowModeMargins
libSceVideoOut| Error:TODO sceVideoOutSetWindowModeMargins
libSceVideoOut| Error:TODO sceVideoOutSetWindowModeMargins
libSceVideoOut| Error:TODO sceVideoOutSetWindowModeMargins
libSceVideoOut| Error:TODO sceVideoOutSetWindowModeMargins
ExceptionHandler| Error:0x7ffa564017b9 base:0x7ffa56400000 F:\psOff-artifact\modules\libScePlayGo.dll
        GoReader::getChunkSize (D:\a\psOff_public\psOff_public\modules\libScePlayGo\chunkreader.cpp:71:0)
ExceptionHandler| Error:0x7ffa56404420 base:0x7ffa56400000 F:\psOff-artifact\modules\libScePlayGo.dll
        scePlayGoGetProgress (D:\a\psOff_public\psOff_public\modules\libScePlayGo\entry.cpp:171:0)
ExceptionHandler| Error:offset:0x0008bf39        base:0x10000000        eboot.bin
ExceptionHandler| Critical Error:Access violation: Read at addr:0x7ffa564017b9 info:0x029edc28 , module base:0x7ffa56400000 F:\psOff-artifact\modules\libScePlayGo.dll
Exiting
saving config files
shutting down VideoOut
deinit Graphics| closed: command buffer watcher
deinit Graphics| done
deinit Graphics| closing command processors
-> destruct CommandProcessor[0]
<- destruct CommandProcessor[0]
deinit Graphics| done
deinit Graphics| closing manager
-> deinit ShaderManager
ERROR:             vkDestroyDescriptorSetLayout: Invalid device [VUID-vkDestroyDescriptorSetLayout-device-parameter]

### Game version you are using

01.00

### Current game status

Intro

### Your renderer version

v.0.5-nightly_27.05.24

### Your psOff version

6cc80207d118aad25e0ef2b607d05370e7181b20

### Upload your log there

[9zwav101ax76lnkr.zip](https://github.com/user-attachments/files/15506527/9zwav101ax76lnkr.zip)

### Upload your screenshots there

https://github.com/SysRay/psOff_compatibility/assets/121258975/ccb13899-b007-49d4-84c3-68c4997ee9f1

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by igor725** [comment]
> GoReader::getChunkSize (D:\a\psOff_public\psOff_public\modules\libScePlayGo\chunkreader.cpp:71:0)

My playgo implementation is not ready for use yet, that's why the pull request is drafted
