### ISSUE TITLE
[CUSA07275]: Blackguards 2

### ISSUE THREAD

**Issue by GAMERRPCS3** [SysRay/psOff_compatibility#294]
### Please, describe what you get

Nothing

Console:Argument Count = 1Arg 0 = psOff
Console:********** LAUNCHER CONTROL ************************************
Console:        File System Root = NONE SPECIFIED
Console:        Launcher Path = NONE SPECIFIED
Console:        Launcher Arguments NONE SPECIFIED
Console:**********/LAUNCHER CONTROL ************************************
[16] mono-ps4.sprx| Image allocation, addr:0x1daf0000 size:0x00251030
Console:[MONO_DLL] start
libkernel| Error:todo sceKernelGetModuleInfo(3)
libkernel| Error:todo sceKernelGetModuleInfo(4)
libkernel| Error:todo sceKernelGetModuleInfo(5)
libkernel| Error:todo sceKernelGetModuleInfo(6)
libkernel| Error:todo sceKernelGetModuleInfo(7)
libkernel| Error:todo sceKernelGetModuleInfo(8)
libkernel| Error:todo sceKernelGetModuleInfo(9)
libkernel| Error:todo sceKernelGetModuleInfo(10)
libkernel| Error:todo sceKernelGetModuleInfo(11)
libkernel| Error:todo sceKernelGetModuleInfo(12)
libkernel| Error:todo sceKernelGetModuleInfo(13)
libkernel| Error:todo sceKernelGetModuleInfo(14)
libkernel| Error:todo sceKernelGetModuleInfo(15)
libkernel| Error:todo sceKernelGetModuleInfo(16)
[17] MonoAssembliesPS4.prx| Image allocation, addr:0x20650000 size:0x02995030
Graphics| Error:todo constBuffer
[13] XaitPlugin.prx| Image allocation, addr:0x46460000 size:0x00241030
ELF64| Critical Error:Can't resolve(XaitPlugin.prx): [0x4668c060] <- 0x00000000 LSG9a6+hIxM#A#B, Object, Global, rela:0 weak:0 test:0x00000000
Exiting
saving config files
shutting down VideoOut
deinit Graphics| closed: command buffer watcher
deinit Graphics| done
deinit Graphics| closing command processors
-> destruct CommandProcessor[0]
<- destruct CommandProcessor[0]
deinit Graphics| done
deinit Graphics| closing manager
-> deinit ShaderManager
<- deinit ShaderManager
-> deinit SamplerManager
<- deinit SamplerManager
-> deinit PipelineManager
<- deinit PipelineManager
-> deinit GpuMemoryManager
ExceptionHandler| Error:0x7ff9f8eead1d base:0x7ff9f80c0000 C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_5cf411dadcb5710d\nvoglv64.dll
        vkGetInstanceProcAddr
ExceptionHandler| Error:0x7ffa19c30b5a base:0x7ffa19be0000 F:\psOff-artifact\psoff_render.dll
        GpuMemoryManager::deinit
ExceptionHandler| Error:0x7ffa19c49dc6 base:0x7ffa19be0000 F:\psOff-artifact\psoff_render.dll
        Manager::deinit
ExceptionHandler| Error:0x7ffa19bf31db base:0x7ffa19be0000 F:\psOff-artifact\psoff_render.dll
        Graphics::deinit
ExceptionHandler| Critical Error:Access violation: Read at addr:0x7ff9f8eead1d info:0xffffffffffffffff , module base:0x7ff9f80c0000 C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_5cf411dadcb5710d\nvoglv64.dll
Exiting

### Game version you are using

01.00

### Current game status

Nothing

### Your renderer version

v.0.5-nightly_27.05.24

### Your psOff version

23f23633ba9b30aa8f4693caeed12a0c80a7cd9c

### Upload your log there

[b4r1v5ttcti7vq93.zip](https://github.com/user-attachments/files/15519194/b4r1v5ttcti7vq93.zip)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by SysRay** [comment]
Can you test it with https://github.com/SysRay/psOff_public/actions/runs/9379700901 pls?

**Comment by GAMERRPCS3** [comment]
Retest

Console:Argument Count = 1Arg 0 = psOff
Console:********** LAUNCHER CONTROL ************************************
Console:        File System Root = NONE SPECIFIED
Console:        Launcher Path = NONE SPECIFIED
Console:        Launcher Arguments NONE SPECIFIED
Console:**********/LAUNCHER CONTROL ************************************
[16] mono-ps4.sprx| Image allocation, addr:0x19c80000 size:0x00251030
Console:[MONO_DLL] start
[17] MonoAssembliesPS4.prx| Image allocation, addr:0x21a60000 size:0x02995030
[13] XaitPlugin.prx| Image allocation, addr:0x41690000 size:0x00241030
ELF64| Critical Error:Can't resolve(XaitPlugin.prx): [0x418bc060] <- 0x00000000 LSG9a6+hIxM#A#B, Object, Global, rela:0 weak:0 test:0x00000000
Exiting
saving config files
shutting down VideoOut
deinit Graphics| closed: command buffer watcher
deinit Graphics| done
deinit Graphics| closing command processors
-> destruct CommandProcessor[0]
<- destruct CommandProcessor[0]
deinit Graphics| done
deinit Graphics| closing manager
-> deinit ShaderManager
<- deinit ShaderManager
-> deinit SamplerManager
<- deinit SamplerManager
-> deinit PipelineManager
<- deinit PipelineManager
-> deinit GpuMemoryManager
[MAINPROCESS] Emulator's process gone!

F:\psOff-artifact>ExceptionHandler| Error:0x7ffa93f9af4a base:0x7ffa93170000 C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_cc569e59ca39c5fe\nvoglv64.dll
        vkGetInstanceProcAddr
ExceptionHandler| Error:0x7ffaabe90505 base:0x7ffaabe70000 F:\psOff-artifact\psoff_render.dll
        createGraphics
ExceptionHandler| Error:0x7ffaabe9d40f base:0x7ffaabe70000 F:\psOff-artifact\psoff_render.dll
        createGraphics
ExceptionHandler| Error:0x7ffaabe74237 base:0x7ffaabe70000 F:\psOff-artifact\psoff_render.dll
        createGraphics
ExceptionHandler| Critical Error:Access violation: Read at addr:0x7ffa93f9af4a info:0x100060128 , module base:0x7ffa93170000 C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_cc569e59ca39c5fe\nvoglv64.dll
Exiting
[2i1m8ortmj11uzuo.zip](https://github.com/user-attachments/files/15930491/2i1m8ortmj11uzuo.zip)
