### ISSUE TITLE
[CUSA12344]: FullBlast

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [SysRay/psOff_compatibility#299]
### Please, describe what you get

Boots, crashes after first screen

### Game version you are using

1.00

### Current game status

Intro

### Your renderer version

v.0.5-nightly_27.04.24

### Your psOff version

156bb3a

### Upload your log there

[20240602-114710.000.p7d.zip](https://github.com/user-attachments/files/15524709/20240602-114710.000.p7d.zip)

### Upload your screenshots there

![image](https://github.com/SysRay/psOff_compatibility/assets/24764335/99ee7a88-a61a-477d-9b13-1a94a0605146)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by SysRay** [comment]
Can you add the console log, please?
