### ISSUE TITLE
[CUSA01587]: Shantae: Risky's Revenge - Director's Cut

### ISSUE THREAD

**Issue by Hermiten** [SysRay/psOff_compatibility#32]
### Please, describe what you get

Crash 

![image](https://github.com/SysRay/psOff_compatibility/assets/151466/f8263fcd-9fee-46d8-ac0e-b4328b9b75ae)

### Game version you are using

01.00

### Current game status

Nothing

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

0db00ad69fcd51855096e94651fb06b13b374c5f

### Upload your log there

[20240415-142332.000.zip](https://github.com/SysRay/psOff_compatibility/files/14979342/20240415-142332.000.zip)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by igor725** [comment]
The same for #27, #28, #29, #30, #31

**Comment by Hermiten** [comment]
> Logs should be uploaded directly to GitHub. Please read README.md and fix your issue report accorsing to it.

I cannot upload .p7d files on github or please tell me how (I can only .txt and some ohers)

**Comment by Hermiten** [comment]
Nvm, I will do it with .zip

**Comment by igor725** [comment]
> > Logs should be uploaded directly to GitHub. Please read README.md and fix your issue report accorsing to it.
> 
> I cannot upload .p7d files on github or please tell me how (I can only .txt and some ohers)

The README clearly says that you should zip your log before uploading it. This way GitHub will accept the file plus it will be compressed, so 300mb log will turn into ~20mb zip archive.

**Comment by Hermiten** [comment]
> > > Logs should be uploaded directly to GitHub. Please read README.md and fix your issue report accorsing to it.
> > 
> > 
> > I cannot upload .p7d files on github or please tell me how (I can only .txt and some ohers)
> 
> The README clearly says that you should zip your log before uploading it. This way GitHub will accept the file plus it will be compressed, so 300mb log will turn into ~20mb zip archive.

Yes, I read it sideways and didn't pay much attention to the last line ... I apologize

It's now 49Mo with ZIP
![image](https://github.com/SysRay/psOff_compatibility/assets/151466/04639306-157e-44a2-9277-bb6cb79a5e47)

**Comment by Hermiten** [comment]
Retest on a better computer:

Crash
Last line on log: Couldn't generate shader: fs_0x351fe32e

Log:
[20240505-212332.000.zip](https://github.com/SysRay/psOff_compatibility/files/15214215/20240505-212332.000.zip)

Emulator version:
https://github.com/SysRay/psOff_public/actions/runs/8959234568

**Comment by SysRay** [comment]
Can you add the console output too, please?
