### ISSUE TITLE
[CUSA06051]: Lethal League

### ISSUE THREAD

**Issue by yaya54840** [SysRay/psOff_compatibility#321]
### Please, describe what you get

The game starts loading and goes to the intro
but no gamepad or keyboard to go further

### Game version you are using

v.100

### Current game status

Intro

### Your emulator version

v.0.6-nightly_30.06.2024

### Upload your log there

[20240604-170154.000.p7d.zip](https://github.com/user-attachments/files/15566429/20240604-170154.000.p7d.zip)

### Upload your screenshots there

![Capture d'écran 2024-06-04 170225](https://github.com/SysRay/psOff_compatibility/assets/47884186/b1c69a53-6c6e-4aad-b025-855775687265)
![Capture d'écran 2024-06-04 170206](https://github.com/SysRay/psOff_compatibility/assets/47884186/14e7816d-0be9-4f37-81ed-0eecc46954c8)
![Capture d'écran 2024-06-04 170251](https://github.com/SysRay/psOff_compatibility/assets/47884186/573fbaa2-671e-4c95-9cd3-6d0a7dbf632e)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by igor725** [comment]
![image](https://github.com/SysRay/psOff_compatibility/assets/40758030/7e24ac06-2e52-430e-a1fe-fcf5a56a1866)
Ingame now
