### ISSUE TITLE
[CUSA02134]: Killing Floor 2

### ISSUE THREAD

**Issue by AussiePlick** [SysRay/psOff_compatibility#346]
### Please, describe what you get

Game boots to first screen for 1 - 2 seconds then crashes.
Not sure if status should be intro or nothing.

### Game version you are using

1.76

### Current game status

Intro

### Your emulator version

v.0.5-nightly_27.05.24

### Upload your log there

[20240608-205447.000.zip](https://github.com/user-attachments/files/15747630/20240608-205447.000.zip)

### Upload your screenshots there

![Killing-Floor-2](https://github.com/SysRay/psOff_compatibility/assets/17723831/60b1f208-480f-443a-ae50-3f6e21502146)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by igor725** [comment]
The game throws an exception in `libc.prx` after `sceGnmDrawInitDefaultHardwareState350` call
