### ISSUE TITLE
[CUSA01264]: Awesomenauts Assemble!

### ISSUE THREAD

**Issue by yaya54840** [SysRay/psOff_compatibility#365]
### Please, describe what you get

crash on loading screen

### Game version you are using

v0.1.00

### Current game status

Nothing

### Your emulator version

v.0.6-nightly_08.06.2024

### Upload your log there

[20240610-171323.000.p7d.zip](https://github.com/user-attachments/files/15775495/20240610-171323.000.p7d.zip)

### Upload your screenshots there

![Capture d'écran 2024-06-10 171303](https://github.com/SysRay/psOff_compatibility/assets/47884186/ba5ed699-2db8-4ec6-9332-ce53ce06f0ea)
![Capture d'écran 2024-06-10 171336](https://github.com/SysRay/psOff_compatibility/assets/47884186/9e0ccc61-c6cc-4f52-9655-e3a945683f0f)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by SysRay** [comment]
Missing Symbol| Name:PfSTDCgNMgc#f#g Lib:libSceNpWebApi(ver:1) Mod:libSceNpWebApi(major:1 minor:1)
