### ISSUE TITLE
[CUSA34848]: Wally and The Fantastic Predators

### ISSUE THREAD

**Issue by Luffykun007** [SysRay/psOff_compatibility#370]
### Please, describe what you get

The game starts, but crashes instantly!

### Game version you are using

01.00

### Current game status

Intro

### Your emulator version

v.0.6-nightly_08.06.2024

### Upload your log there

[20240611-122350.000.zip](https://github.com/user-attachments/files/15791458/20240611-122350.000.zip)

### Upload your screenshots there

![Captura de Tela (54)](https://github.com/SysRay/psOff_compatibility/assets/26087621/7af2af91-d2ad-4d1a-915f-79e2cbf457bd)
![Captura de Tela (52)](https://github.com/SysRay/psOff_compatibility/assets/26087621/4bf775d8-6e50-477d-a7a0-63b3f68250fe)
![Captura de Tela (50)](https://github.com/SysRay/psOff_compatibility/assets/26087621/806fea71-827a-4545-8024-7c62407b202d)
![Captura de Tela (53)](https://github.com/SysRay/psOff_compatibility/assets/26087621/3a55a8bf-b2db-4a35-bd30-ddb102603fe1)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by igor725** [comment]
Log you posted has no crash info, please send the terminal output there in comment section

**Comment by Luffykun007** [comment]
> Log you posted has no crash info, please send the terminal output there in comment section

And how I do it?

**Comment by igor725** [comment]
> > Log you posted has no crash info, please send the terminal output there in comment section
> 
> And how I do it?

How do you run the games? Do you use launcher or command line?

**Comment by Luffykun007** [comment]
> How do you run the games? Do you use launcher or command line?

Launcher bro

**Comment by igor725** [comment]
> > How do you run the games? Do you use launcher or command line?
> 
> Launcher bro

Then just make double click on this screen after the game crashes, this way you will copy the output.

![image](https://github.com/SysRay/psOff_compatibility/assets/40758030/2b224066-a961-44a7-81eb-918f854b9aa5)

**Comment by Luffykun007** [comment]
> Then just make double click on this screen after the game crashes, this way you will copy the output.
> 
> ![image](https://private-user-images.githubusercontent.com/40758030/338681630-2b224066-a961-44a7-81eb-918f854b9aa5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMjg3MTIsIm5iZiI6MTcxODEyODQxMiwicGF0aCI6Ii80MDc1ODAzMC8zMzg2ODE2MzAtMmIyMjQwNjYtYTk2MS00NGE3LTgxZWItOTE4Zjg1NGI5YWE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDE3NTMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0N2Y3NWY4ZDMxMjcyNzA3NjlkMDQyNDhlNDkxYzIyMmUyZGJhYTk2NDc1ZWZlMTk4YWIzMDljYzk3YmUwMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B5SMidLZWC0U2gIFePpXTeXX0XUgoNPGY9eB32D6UqY)

Thanks bro

[Log_terminal.zip](https://github.com/user-attachments/files/15793040/Log_terminal.zip)
