### ISSUE TITLE
[CUSA05010]: Oceanhorn

### ISSUE THREAD

**Issue by ArbestRi02** [SysRay/psOff_compatibility#380]
### Please, describe what you get

Just crashes before anything happens.

### Game version you are using

v1.00

### Current game status

Nothing

### Your emulator version

v0.5

### Upload your log there

Config logging.json loaded successfully
Config graphics.json loaded successfully
Config audio.json loaded successfully
Config general.json loaded successfully
Config resolve.json loaded successfully
Config controls.json loaded successfully
Renderer version: v.0.5
[3] eboot.bin| Image allocation, addr:0x10000000 size:0x006e1030
[4] libc.prx| Image allocation, addr:0x20000000 size:0x000e5030
[5] libSceFios2.prx| Image allocation, addr:0x300f0000 size:0x0018d030
[6] libfmod.prx| Image allocation, addr:0x40280000 size:0x001c1030
libSceNgs2| Error:todo sceNgs2RackGetInfo
Selected GPU:NVIDIA GeForce RTX 2060 SUPER api:1.3.278
libSceNgs2| Error:todo sceNgs2RackGetInfo
libSceAudioOut| Error:Failed to open PadSpeaker audio device: No such device.
libSceSystemService| Error:todo sceSystemServiceHideSplashScreen
todo constBuffer
vulkanHelper| Critical Error:Couldn't vkQueueSubmit Transfer VK_ERROR_DEVICE_LOST
Exiting
saving config files
shutting down VideoOut
deinit Graphics| closed: command buffer watcher
deinit Graphics| done
deinit Graphics| closing command processors
-> destruct CommandProcessor[0]
Process exited with code 3221226505

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by yaya54840** [comment]
[log.zip](https://github.com/user-attachments/files/15846137/log.zip)
![Capture d'écran 2024-06-15 095712](https://github.com/SysRay/psOff_compatibility/assets/47884186/885e73eb-2d57-465d-88d5-dff1a460b8e7)
![Capture d'écran 2024-06-15 095849](https://github.com/SysRay/psOff_compatibility/assets/47884186/0aa93432-d7c5-4df7-9927-2141030b3bd4)
Hi
This game works
audio ok
poor graphics
In Game
