### ISSUE TITLE
[CUSA01113]: Gravity Rush™ Remastered

### ISSUE THREAD

**Issue by Graubek** [SysRay/psOff_compatibility#42]
### Please, describe what you get

Game crashes right after launch.

### Game version you are using

01.00

### Current game status

Nothing

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

d4fe099

### Upload your log there

[20240415-170512.000.zip](https://github.com/SysRay/psOff_compatibility/files/14980891/20240415-170512.000.zip)

### Upload your screenshots there

![rush](https://github.com/SysRay/psOff_compatibility/assets/58905125/088bc617-ce58-464d-b1c1-6881972529e9)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by gandalfthewhite19890404** [comment]
Unimplemented - _sceFiberInitializeImpl

**Comment by GamingDucking** [comment]
Retest
