### ISSUE TITLE
[CUSA09415]: Undertale

### ISSUE THREAD

**Issue by igor725** [SysRay/psOff_compatibility#5]
### Please, describe what you get

Might be actually playable, need more info. Someone should try to beat the game on emulator.

### Game version you are using

01.00

### Current game status

Ingame

### Version

v.0.4-beta (Default)

### psOff-libs version you are using

0a845da6825bb256a84ff918caa699fbfb70a4a9

### Upload your log there

[20240408-020358.000.zip](https://github.com/SysRay/psOff_compatibility/files/14899303/20240408-020358.000.zip)

### Yes, I agree

- [x] Yes, I read the rules and did everything according to them

**Comment by cldgit** [comment]
During Mettaton's battle on pacifist or neutral it soft-locks you by trying to bring up the PlayStation 4 on screen keyboard so this game probably won't be beatable until there's a fix or implementation of the onscreen keyboard
![image](https://github.com/SysRay/psOff_compatibility/assets/123279742/cd49d436-4a57-47c6-acc0-4a0084123820)

**Comment by igor725** [comment]
> During Mettaton's battle on pacifist or neutral it soft-locks you by trying to bring up the PlayStation 4 on screen keyboard so this game probably won't be beatable until there's a fix or implementation of the onscreen keyboard
> ![image](https://github.com/SysRay/psOff_compatibility/assets/123279742/cd49d436-4a57-47c6-acc0-4a0084123820)
> 
> 

Could you please send some logs? I want to know exactly what part of Ime library should be implemented, so I can do this tomorrow.

**Comment by cldgit** [comment]
Yeah of course
[20240606-210938.000.zip](https://github.com/user-attachments/files/15688321/20240606-210938.000.zip)

**Comment by igor725** [comment]
> Yeah of course
> [20240606-210938.000.zip](https://github.com/user-attachments/files/15688321/20240606-210938.000.zip)
> 

Yeah, thank you. I'll check them later this day.

**Comment by igor725** [comment]
Could you please retest it with [this build](<https://github.com/SysRay/psOff_public/actions/runs/9421468862?pr=211>)? It should show you the input dialog.

**Comment by cldgit** [comment]
> Could you please retest it with [this build](https://github.com/SysRay/psOff_public/actions/runs/9421538351?pr=211)? It should show you the input dialog.

I got back to that part of the fight and for some reason in the prompt there was already those question marks, I CTRL+A'd and tried typing and it crashed on me

![image](https://github.com/SysRay/psOff_compatibility/assets/123279742/a83d4c03-2d3a-453f-83f7-608dbc80e899)

[20240607-201227.000.zip](https://github.com/user-attachments/files/15744995/20240607-201227.000.zip)

**Comment by igor725** [comment]
> > for some reason in the prompt there was already those question marks, I CTRL+A'd and tried typing and it crashed on me

Oh well, guess I forgot to fill the memory block eith zeros. But it shouldnt crash, something weird going on.

**Comment by igor725** [comment]
Should not crash with <https://github.com/SysRay/psOff_public/actions/runs/9423825847?pr=211>

**Comment by igor725** [comment]
Updated a bit more, it's better to test with <https://github.com/SysRay/psOff_public/actions/runs/9424255790?pr=211>

**Comment by cldgit** [comment]
The on screen keyboard worked this time!!! i got to beat mettaton!!
![undertale-1](https://github.com/SysRay/psOff_compatibility/assets/123279742/c2f92505-63e0-4385-82fc-77f2741e2ac5)
![image](https://github.com/SysRay/psOff_compatibility/assets/123279742/55244209-2e8a-4742-8d22-b63c9b3d93d7)

I'll try completing the game from here

**Comment by cldgit** [comment]
![undertalep-3](https://github.com/SysRay/psOff_compatibility/assets/123279742/9cf313c7-8f39-499e-a3c1-187ccdf996ee)
I was able to complete the game (Well the normal ending at least) without anymore issues , I'm sure it's playable through the true pacifist and genocide route

**Comment by igor725** [comment]
Thank you for tests :)
