### ISSUE TITLE
[CUSA33393]: Fate/Samurai Remmant

### ISSUE THREAD

**Issue by Digote** [SysRay/psOff_compatibility#52]
### Please, describe what you get

Running this title results in an **Critical Error:Missing Symbol| Name:V2u3WLrwh64#v#w Lib:libSceUlt(ver:1) Mod:libSceUlt(major:1 minor:1)**

Error:todo sceRemoteplayInitialize
Error:TODO: sceSharePlayInitialize
Error:todo sceGameLiveStreamingInitialize
Error:todo sceAppContentGetAddcontInfoList
Error:TODO: scePlayGoSetToDoList
Error:TODO: scePlayGoSetToDoList
Error:0x14001fd27
Error:0x14001bab7
Error:0x140014353
Error:0x005d5308
Critical Error:Missing Symbol| Name:V2u3WLrwh64#v#w Lib:libSceUlt(ver:1) Mod:libSceUlt(major:1 minor:1)
Exiting

### Game version you are using

1.0

### Current game status

Nothing

### Your emulator version

v0.5-preview-0

### psOff-libs version you are using

https://github.com/SysRay/psOff_public/actions/runs/8695757577

### Upload your log there

[20240415-183507.000.zip](https://github.com/SysRay/psOff_compatibility/files/14984518/20240415-183507.000.zip)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by gandalfthewhite19890404** [comment]
Resolved symbol - sceNgs2ReportRegisterHandler

**Comment by GamingDucking** [comment]
Retest
