### ISSUE TITLE
[CUSA03454]: Super Meat Boy!

### ISSUE THREAD

**Issue by Emulator-Team-2** [SysRay/psOff_compatibility#54]
### Please, describe what you get

The game crashes right after launch with this error:
```
Critical Error:Missing Symbol| Name:ekGJmmoc8j4#B#C Lib:libSceNgs2(ver:1) Mod:libSceNgs2(major:1 minor:1)
Exiting
```

### Game version you are using

01.00

### Current game status

Nothing

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

48bc506cf54b94fc756231176fc8b745ec252585

### Upload your log there

[20240416-123445.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/14995498/20240416-123445.000.p7d.zip)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by Emulator-Team-2** [comment]
With (libSceNgs2) in sce_module, the game starts without this crash and goes Ingame.

![1](https://github.com/SysRay/psOff_compatibility/assets/38318848/2bd4907b-cc94-40bd-97c8-0b6cb9db26ca)

**Comment by igor725** [comment]
Please, retest with <https://github.com/SysRay/psOff_public/actions/runs/8704815102>, should run without libSceNgs2.prx (but without any sound output).

**Comment by Emulator-Team-2** [comment]
@igor725 
The game crashes right after launch on this build without (libSceNgs2).
Log:
[20240416-135951.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/14996397/20240416-135951.000.p7d.zip)

**Comment by igor725** [comment]
> @igor725 The game crashes right after launch on this build without (libSceNgs2). Log: [20240416-135951.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/14996397/20240416-135951.000.p7d.zip)

Weird... I'll look into it later

**Comment by igor725** [comment]
> @igor725 The game crashes right after launch on this build without (libSceNgs2). Log: [20240416-135951.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/14996397/20240416-135951.000.p7d.zip)

<https://github.com/igor725/psOff_public/actions/runs/8708816292> ultimately fixes this issue, now you can boot your game without `libSceNGs2.prx` installed. The game will run with no sound tho.

**Comment by igor725** [comment]
Oh, its ingame actually... Alr then
