### ISSUE TITLE
[CUSA00491]: Spelunky

### ISSUE THREAD

**Issue by Emulator-Team-2** [SysRay/psOff_compatibility#56]
### Please, describe what you get

The game crashes right after launch with this error:
```
Critical Error:Missing Symbol| Name:WIWV1Qd7PFU#X#Y Lib:libSceUlt(ver:1) Mod:libSceUlt(major:1 minor:1)
Exiting
```

### Game version you are using

01.01

### Current game status

Nothing

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

48bc506cf54b94fc756231176fc8b745ec252585

### Upload your log there

[20240416-142341.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/14996665/20240416-142341.000.p7d.zip)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by gandalfthewhite19890404** [comment]
Unimplemnted - sceUltWaitingQueueResourcePoolGetWorkAreaSize

**Comment by Emulator-Team-2** [comment]
## Update:

### Please, describe what you get

The game still crashes right after launch.
But now with a different error:
```
Critical Error:QueuePop| queue: 00000000029930F0, data: 00000000B2FEFC60
Exiting

unknown Imagedim for 4
```

### Game version you are using

01.01

### Current game status

Nothing

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

5ea4a19d6169e9bfa956279b0844b84949f04418

### Upload your log there

[20240424-192536.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/15098173/20240424-192536.000.p7d.zip)

**Comment by Emulator-Team-2** [comment]
## Update:

The game still crashes right after launch.
But now with a different error:
```
Critical Error:QueuePop| queue: 00000000029430F0, data: 00000000B8C4FC60
Exiting

(fs_0x7b6e4b60) Compile error, line:0 column:0 | (Expected Coordinate to have at least 2 components, but given only 1
  %54 = OpImageSampleImplicitLod %v4float %52 %32
)
Optimize failed
Critical Error:Couldn't generate shader: fs_0x7b6e4b60
Exiting
```

**Current game status:** Nothing.

**Emulator version:** v.0.5-preview-0
**psOff-libs version:**
8971baae0d5e6cdde85e2c16f062db7aa079804a

Log:
[20240428-023945.000.zip](https://github.com/SysRay/psOff_compatibility/files/15140404/20240428-023945.000.zip)

**Comment by Emulator-Team-2** [comment]
## Update:

The game still crashes right after launch.
But now with a different error.
```
Critical Error:QueuePop| queue: 00000001205030F0, data: 000000000F1AFC60
Exiting
Error:todo constBuffer
unknown Imagedim for 4
```

**Current game status:** Nothing.

**Renderer version:** v.0.5-nightly_04.05.24
**psOff version:**
cb60bfd95a8f71115db63c56141bfd2c64362936

Log:
[20240504-233738.000.zip](https://github.com/SysRay/psOff_compatibility/files/15211042/20240504-233738.000.zip)

**Comment by Emulator-Team-2** [comment]
## Update:

The game still crashes right after launch.
But now it shows the logo before the crash.
```
libSceUlt| Critical Error:QueuePop| queue: 00000001205030F0, data: 0000000019D8FC60
Exiting
```
```
ExceptionHandler| Error:0x7ffd7555a959 base:0x7ffd75500000 C:\Windows\SYSTEM32\vulkan-1.dll
        vkResetEvent
ExceptionHandler| Error:0x7ffd75cd6988 base:0x7ffd75c90000 E:\PS4\psOff\psoff_render.dll
        createGraphics
ExceptionHandler| Error:0x7ffd75cd5a10 base:0x7ffd75c90000 E:\PS4\psOff\psoff_render.dll
        createGraphics
ExceptionHandler| Error:0x7ffd75cbf9df base:0x7ffd75c90000 E:\PS4\psOff\psoff_render.dll
        createGraphics
ExceptionHandler| Critical Error:Access violation: Read at addr:0x7ffd7555a959 info:0xffffffffffffffff , module base:0x7ffd75500000 C:\Windows\SYSTEM32\vulkan-1.dll
Exiting
```

**Current game status:** Nothing.

**Renderer version:** v.0.6-nightly_08.06.2024  
**psOff version:**
98ef80dfdd8554aab5edccb09b56dd41bb1340f6

Log:
[20240609-141158.000.zip](https://github.com/user-attachments/files/15752339/20240609-141158.000.zip)

**Comment by Luffykun007** [comment]
Update: The game now shows this screen but instantly closes a second later!

![Captura de Tela (95)](https://github.com/SysRay/psOff_compatibility/assets/26087621/82114f2c-ba24-4d91-9254-aa6abc528d71)
