### ISSUE TITLE
[CUSA04135]: Toki Tori 2+

### ISSUE THREAD

**Issue by Emulator-Team-2** [SysRay/psOff_compatibility#58]
### Please, describe what you get

The game crashes right after launch with this error:
```
Critical Error:Missing Symbol| Name:M4LYATRhRUE#N#N Lib:libSceNgs2(ver:1) Mod:libSceNgs2(major:1 minor:1)
Exiting
```

### Game version you are using

01.00

### Current game status

Nothing

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

48bc506cf54b94fc756231176fc8b745ec252585

### Upload your log there

[20240416-144053.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/14996866/20240416-144053.000.p7d.zip)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by gandalfthewhite19890404** [comment]
Resolved symbol - sceNgs2RackGetInfo

**Comment by Emulator-Team-2** [comment]
## Update:

### Please, describe what you get

The game no longer crashes right after launch.
Now it hangs there, as in the screenshot below, the emulator is waiting for something.

### Game version you are using

01.00

### Current game status

Intro

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

e7f77e429c3faabb90c3a4021e949fb2ca09c082

### Upload your log there

[20240418-114445.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/15023080/20240418-114445.000.p7d.zip)

### Upload your screenshots there

![1](https://github.com/SysRay/psOff_compatibility/assets/38318848/e96b1035-96da-45a2-a542-4699204991b7)
