### ISSUE TITLE
[CUSA09920]: Owlboy

### ISSUE THREAD

**Issue by Emulator-Team-2** [SysRay/psOff_compatibility#59]
### Please, describe what you get

The game crashes right after launch with this error:
```
Critical Error:Missing Symbol| Name:xa8oL9dmXkM#B#C Lib:libSceNgs2(ver:1) Mod:libSceNgs2(major:1 minor:1)
Exiting
```

### Game version you are using

01.00

### Current game status

Nothing

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

48bc506cf54b94fc756231176fc8b745ec252585

### Upload your log there

[20240416-144606.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/14996933/20240416-144606.000.p7d.zip)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by gandalfthewhite19890404** [comment]
Resolved symbol - sceNgs2PanInit

**Comment by Emulator-Team-2** [comment]
## Update:

### Please, describe what you get

The game no longer crashes right after launch.
Now it stay on the black screen after (intro / logo), as in the screenshot below, the emulator is waiting for something.

### Game version you are using

01.00

### Current game status

Intro

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

a2fc208181eff1a38af873a9797f49cea260eb40

### Upload your log there

[20240418-160227.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/15025992/20240418-160227.000.p7d.zip)

### Upload your screenshots there

![1](https://github.com/SysRay/psOff_compatibility/assets/38318848/076abd69-002b-4ef0-9a86-e64e6bea77c1)

<details> 
<summary>(More - screenshots)</summary>

![2](https://github.com/SysRay/psOff_compatibility/assets/38318848/9294cced-b47d-486b-8989-e23a2f08146c)

</details>

**Comment by Emulator-Team-2** [comment]
## Update:

The game still remains on a black screen after the intro.

The log shows this error:
```
Error:todo constBuffer
```

**Current game status:** Intro.

**Renderer version:** v.0.5-nightly_04.05.24  
**psOff version:**
4161cbba3b8799559d8c0a5def574f4a6c483caa

Log:
[20240512-152233.000.zip](https://github.com/SysRay/psOff_compatibility/files/15286402/20240512-152233.000.zip)

**Comment by Emulator-Team-2** [comment]
## Update:

The game still remains on a black screen after the intro.

**Current game status:** Nothing.

**Renderer version:** v.0.6-nightly_08.06.2024  
**psOff version:**
98ef80dfdd8554aab5edccb09b56dd41bb1340f6

Log:
[20240609-144108.001.zip](https://github.com/user-attachments/files/15752539/20240609-144108.001.zip)
