### ISSUE TITLE
[CUSA00382]: FEZ

### ISSUE THREAD

**Issue by Emulator-Team-2** [SysRay/psOff_compatibility#60]
### Please, describe what you get

The game crashes right after launch with this error:
```
Critical Error:Missing Symbol| Name:WIWV1Qd7PFU#X#Y Lib:libSceUlt(ver:1) Mod:libSceUlt(major:1 minor:1)
Exiting
```

### Game version you are using

01.00

### Current game status

Nothing

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

48bc506cf54b94fc756231176fc8b745ec252585

### Upload your log there

[20240416-145832.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/14997088/20240416-145832.000.p7d.zip)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by gandalfthewhite19890404** [comment]
Resolved symbol - sceUltWaitingQueueResourcePoolGetWorkAreaSize

**Comment by Emulator-Team-2** [comment]
## Update:

### Please, describe what you get

The game still crashes right after launch.
But now with a different error:
```
Critical Error:QueuePop| queue: 0000000004D10030, data: 000000005125FC60
Exiting
Error:todo sceNgs2SystemCreateWithAllocator(000000000CE2F8D8, 0000000010D46770, 0000000010DC0568)
Console:sceNgs2SystemCreateWithAllocator is falied | iResult(0x804a0081)
Error:todo sceSystemServiceHideSplashScreen
Critical Error:0x00000000 not in m_deviceMemoryList
Exiting
Assertion failed: numElements > 4, file D:\a\psOff\psOff\tools\sb2spirv\lib\src/typeId.h, line 196
```

### Game version you are using

01.00

### Current game status

Nothing

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

5ea4a19d6169e9bfa956279b0844b84949f04418

### Upload your log there

[20240424-193959.001.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/15098308/20240424-193959.001.p7d.zip)

**Comment by Emulator-Team-2** [comment]
## Update:

The game still crashes right after launch.
But now with a different error:
```
Critical Error:QueuePop| queue: 00000000056B0030, data: 000000005825FC60
Exiting
Error:todo sceNgs2SystemCreateWithAllocator(000000000D7FF8D8, 0000000010D46770, 0000000010DC0568)
Console:sceNgs2RackGetVoiceHandle is falied | iResult(0x804a0302)

Critical Error:0x00000000 not in m_deviceMemoryList
Exiting
Assertion failed: numElements > 16, file D:\a\psOff\psOff\tools\sb2spirv\lib\src/typeId.h, line 200
```

**Current game status:** Nothing.

**Emulator version:** v.0.5-preview-0
**psOff-libs version:**
8971baae0d5e6cdde85e2c16f062db7aa079804a

Log:
[20240428-024653.000.zip](https://github.com/SysRay/psOff_compatibility/files/15140411/20240428-024653.000.zip)

**Comment by Emulator-Team-2** [comment]
## Update:

The game still crashes right after launch.
```
libSceUlt| Critical Error:QueuePop| queue: 0000000120090030, data: 0000000019CBFC60
Exiting
Console:Audio out started (port#1,512[samples],48000[Hz],8[ch])
Console:  Buffer[0] : 19dafd50
Console:  Buffer[1] : 19db7d50
```
```
ExceptionHandler| Error:0x7ffd72edaf4a base:0x7ffd720b0000 C:\Windows\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_cc569e59ca39c5fe\nvoglv64.dll
        vkGetInstanceProcAddr
ExceptionHandler| Error:0x7ffd71870505 base:0x7ffd71850000 E:\PS4\psOff\psoff_render.dll
        createGraphics
ExceptionHandler| Error:0x7ffd7187d40f base:0x7ffd71850000 E:\PS4\psOff\psoff_render.dll
        createGraphics
ExceptionHandler| Error:0x7ffd71854237 base:0x7ffd71850000 E:\PS4\psOff\psoff_render.dll
        createGraphics
ExceptionHandler| Critical Error:Access violation: Read at addr:0x7ffd72edaf4a info:0x100080128 , module base:0x7ffd720b0000 C:\Windows\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_cc569e59ca39c5fe\nvoglv64.dll
Exiting
```

**Current game status:** Nothing.

**Renderer version:** v.0.6-nightly_08.06.2024  
**psOff version:**
98ef80dfdd8554aab5edccb09b56dd41bb1340f6

Log:
[20240609-144438.000.zip](https://github.com/user-attachments/files/15752552/20240609-144438.000.zip)
