### ISSUE TITLE
[CUSA17789]: Skelattack

### ISSUE THREAD

**Issue by Emulator-Team-2** [SysRay/psOff_compatibility#65]
### Please, describe what you get

The game crashes right after launch with this error:
```
Critical Error:Missing Symbol| Name:u5oqtlIP+Fw#b#H Lib:libSceNetCtlForNpToolkit(ver:1) Mod:libSceNetCtl(major:1 minor:1)
Exiting
```

### Game version you are using

01.00

### Current game status

Nothing

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

48bc506cf54b94fc756231176fc8b745ec252585

### Upload your log there

[20240416-162709.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/14998341/20240416-162709.000.p7d.zip)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by gandalfthewhite19890404** [comment]
Resolved symbol - sceNetCtlCheckCallbackForNpToolkit

**Comment by Emulator-Team-2** [comment]
## Update:

### Please, describe what you get

The game no longer crashes right after launch.
Goes Ingame now, but with Broken graphics.

The emulator spams the log with such errors.
```
Error:NO Sampled Image 0x163b62800 width:2048 height:2048 type:9 tiling:0x5
Error:NO Sampled Image 0x164b62800 width:2048 height:2048 type:9 tiling:0x5
Error:NO Sampled Image 0x163b62800 width:2048 height:2048 type:9 tiling:0x5
Error:NO Sampled Image 0x167b62800 width:2048 height:1024 type:9 tiling:0x5
```

### Game version you are using

01.00

### Current game status

Ingame

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

a2fc208181eff1a38af873a9797f49cea260eb40

### Upload your log there

[20240418-174725.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/15027313/20240418-174725.000.p7d.zip)

### Upload your screenshots there

![1](https://github.com/SysRay/psOff_compatibility/assets/38318848/5cbbd55c-34e5-436d-8978-233fac312ef7)

**Comment by Emulator-Team-2** [comment]
## Update:

The game is now crashing with this error:
```
Critical Error:NO Sampled Image 0x1a182fb00 width:512 height:256 type:9 tiling:0x5
Exiting
```

**Current game status:** Nothing.

**Emulator version:** v.0.5-preview-0
**psOff-libs version:**
8971baae0d5e6cdde85e2c16f062db7aa079804a

Log:
[20240428-030637.000.zip](https://github.com/SysRay/psOff_compatibility/files/15140422/20240428-030637.000.zip)

**Comment by Emulator-Team-2** [comment]
## Update:

The game no longer crashes right after launch.

**Current game status:** Ingame.

**Renderer version:** v.0.5-nightly_04.05.24
**psOff version:**
cb60bfd95a8f71115db63c56141bfd2c64362936

Log:
[20240505-001014.000.zip](https://github.com/SysRay/psOff_compatibility/files/15211121/20240505-001014.000.zip)

![1](https://github.com/SysRay/psOff_compatibility/assets/38318848/57948b66-3c7a-4c5e-9f0f-a1ce3d7213d4)
