### ISSUE TITLE
[CUSA00706]: How to Survive: Storm Warning Edition

### ISSUE THREAD

**Issue by Emulator-Team-2** [SysRay/psOff_compatibility#66]
### Please, describe what you get

The game crashes right after launch with this error:
```
Critical Error:Missing Symbol| Name:amuBfI-AQc4#O#P Lib:libSceRudp(ver:1) Mod:libSceRudp(major:0 minor:0)
Exiting
```

### Game version you are using

01.00

### Current game status

Nothing

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

48bc506cf54b94fc756231176fc8b745ec252585

### Upload your log there

[20240416-163451.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/14998478/20240416-163451.000.p7d.zip)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by gandalfthewhite19890404** [comment]
Resolved symbol - sceRudpInit

**Comment by Emulator-Team-2** [comment]
## Update:

The game still crashes right after launch.
But now with a different error.
```
Error:todo sceNgs2SystemCreate(0000000000000000, 000000000468FA20, 000000013F383708)
Error:todo sceNgs2RackCreate(00000001019FEDA0, 12288, 0000000000000000, 000000000468F950, 000000013F4847B8)
Error:todo sceNgs2RackCreate(00000001019FEDA0, 4096, 0000000000000000, 000000000468F990, 000000013F383718)
Error:todo sceNgs2RackCreate(00000001019FEDA0, 4096, 0000000000000000, 000000000468F990, 000000013F383730)
Error:offset:0x000d3d59  base:0x10000000        eboot.bin
Critical Error:Access violation: Read at addr:0x100d3d59 info:0x00000000 , module base:0x10000000 eboot.bin
Exiting
```

**Current game status:** Nothing.

**Renderer version:** v.0.5-nightly_04.05.24  
**psOff version:**
4161cbba3b8799559d8c0a5def574f4a6c483caa

Log:
[20240512-120119.000.zip](https://github.com/SysRay/psOff_compatibility/files/15285774/20240512-120119.000.zip)

**Comment by Emulator-Team-2** [comment]
## Update:

The game still crashes right after launch.
```
ExceptionHandler| Error:offset:0x000d3d59        base:0x10000000        eboot.bin
ExceptionHandler| Critical Error:Access violation: Read at addr:0x100d3d59 info:0x00000000 , module base:0x10000000 eboot.bin
Exiting
```
```
ExceptionHandler| Error:0x7ffd72edaf4a base:0x7ffd720b0000 C:\Windows\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_cc569e59ca39c5fe\nvoglv64.dll
        vkGetInstanceProcAddr
ExceptionHandler| Error:0x7ffd71870505 base:0x7ffd71850000 E:\PS4\psOff\psoff_render.dll
        createGraphics
ExceptionHandler| Error:0x7ffd7187d40f base:0x7ffd71850000 E:\PS4\psOff\psoff_render.dll
        createGraphics
ExceptionHandler| Error:0x7ffd71854237 base:0x7ffd71850000 E:\PS4\psOff\psoff_render.dll
        createGraphics
ExceptionHandler| Critical Error:Access violation: Read at addr:0x7ffd72edaf4a info:0x101a00128 , module base:0x7ffd720b0000 C:\Windows\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_cc569e59ca39c5fe\nvoglv64.dll
Exiting
```

**Current game status:** Nothing.

**Renderer version:** v.0.6-nightly_08.06.2024  
**psOff version:**
98ef80dfdd8554aab5edccb09b56dd41bb1340f6

Log:
[20240609-153141.000.zip](https://github.com/user-attachments/files/15752670/20240609-153141.000.zip)
