### ISSUE TITLE
[CUSA06733]: Koihime Enbu RyoRaiRai

### ISSUE THREAD

**Issue by Emulator-Team-2** [SysRay/psOff_compatibility#69]
### Please, describe what you get

The game crashes right after launch with this error:
```
Critical Error:Missing Symbol| Name:amuBfI-AQc4#f#e Lib:libSceRudp(ver:1) Mod:libSceRudp(major:0 minor:0)
Exiting
```

### Game version you are using

01.00

### Current game status

Nothing

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

48bc506cf54b94fc756231176fc8b745ec252585

### Upload your log there

[20240416-165231.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/14998730/20240416-165231.000.p7d.zip)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by gandalfthewhite19890404** [comment]
Unimplemented - sceRudpInit

**Comment by Emulator-Team-2** [comment]
## Update:

The game still crashes right after launch.
But now with a different error.

New missing symbol:
```
Critical Error:Missing Symbol| Name:EkqGLxWC-S0#p#n Lib:libSceUsbd(ver:1) Mod:libSceUsbd(major:1 minor:1)
Exiting
```
```
Error:offset:0x0005a959  base:0x7ff83dfb0000    C:\Windows\SYSTEM32\vulkan-1.dll
Error:offset:0x00059468  base:0x7ff83e250000    C:\Users\Z490\Desktop\psOff\psoff_render.dll
Error:offset:0x0005849f  base:0x7ff83e250000    C:\Users\Z490\Desktop\psOff\psoff_render.dll
Error:offset:0x00040dcf  base:0x7ff83e250000    C:\Users\Z490\Desktop\psOff\psoff_render.dll
Critical Error:Access violation: Read at addr:0x7ff83e00a959 info:0xffffffffffffffff , module base:0x7ff83dfb0000 C:\Windows\SYSTEM32\vulkan-1.dll
Exiting
```

**Current game status:** Nothing.

**Emulator version:** v.0.5-nightly_29.04.24-fix 
**psOff-libs version:**
ef8106ac3611135c30ef7ac92ec8b11b124b1f11

Log:
[20240502-153803.000.zip](https://github.com/SysRay/psOff_compatibility/files/15189159/20240502-153803.000.zip)

**Comment by gandalfthewhite19890404** [comment]
Missing - sceUsbdHandleEvents

**Comment by Emulator-Team-2** [comment]
## Update:

The game still crashes right after launch.

Missing Symbol:
```
Critical Error:Missing Symbol| Name:EkqGLxWC-S0#p#n Lib:libSceUsbd(ver:1) Mod:libSceUsbd(major:1 minor:1)
Exiting
```
```
Error:0x7fff5819a959 base:0x7fff58140000 C:\Windows\SYSTEM32\vulkan-1.dll
        vkResetEvent
Error:0x7fff587d9208 base:0x7fff58780000 E:\PS4\psOff\psoff_render.dll
        ShaderData::~ShaderData
Error:0x7fff587d823f base:0x7fff58780000 E:\PS4\psOff\psoff_render.dll
        std::use_facet<std::codecvt<char,char,_Mbstatet> >
Error:0x7fff587c0b6f base:0x7fff58780000 E:\PS4\psOff\psoff_render.dll
        ShaderManager::deinit
Critical Error:Access violation: Read at addr:0x7fff5819a959 info:0xffffffffffffffff , module base:0x7fff58140000 C:\Windows\SYSTEM32\vulkan-1.dll
Exiting
```

**Current game status:** Nothing.

**Renderer version:** v.0.5-nightly_04.05.24  
**psOff version:**
4161cbba3b8799559d8c0a5def574f4a6c483caa

Log:
[20240512-124915.000.zip](https://github.com/SysRay/psOff_compatibility/files/15285936/20240512-124915.000.zip)

**Comment by Emulator-Team-2** [comment]
## Update:

New errors:
```
Error:ParseRIFF: ffmpeg failed to read passed data: -1094995529
```
```
Critical Error:0x00000100 not in m_deviceMemoryList
Exiting
unknown Imagedim for 4
```
```
convertSbFormat unknown 0 0 0
getImageType undefined: 6
getImageType undefined: 6
unknown Imagedim for 6
```

**Current game status:** Intro?

**Renderer version:** v.0.5-nightly_04.05.24  
**psOff version:**
bea5f0621dd144c36923d591e8d0c08a58170cd1

Log:
[20240517-220214.000.zip](https://github.com/SysRay/psOff_compatibility/files/15357946/20240517-220214.000.zip)
[20240517-220321.000.zip](https://github.com/SysRay/psOff_compatibility/files/15357948/20240517-220321.000.zip)
[20240517-220708.001.zip](https://github.com/SysRay/psOff_compatibility/files/15357950/20240517-220708.001.zip)

![1](https://github.com/SysRay/psOff_compatibility/assets/38318848/e0c6e68d-0faa-46ed-a37c-3b909c5ee130)

**Comment by Emulator-Team-2** [comment]
## Update:

The graphics are still broken, looking the same as in the previous test.
```
libSceNgs2| Error:channel layout not set
```

**Current game status:** Nothing.

**Renderer version:** v.0.6-nightly_08.06.2024  
**psOff version:**
98ef80dfdd8554aab5edccb09b56dd41bb1340f6

Log:
[20240609-154623.000.zip](https://github.com/user-attachments/files/15752723/20240609-154623.000.zip)
