### ISSUE TITLE
[CUSA03475]: DENGEKI BUNKO FIGHTING CLIMAX IGNITION

### ISSUE THREAD

**Issue by Emulator-Team-2** [SysRay/psOff_compatibility#70]
### Please, describe what you get

The game crashes right after launch with this error:
```
Critical Error:Missing Symbol| Name:VjhsmxpcezI#X#X Lib:libSceAudiodec(ver:1) Mod:libSceAudiodec(major:1 minor:1)
Exiting
```

### Game version you are using

01.04

### Current game status

Nothing

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

48bc506cf54b94fc756231176fc8b745ec252585

### Upload your log there

[20240424-025631.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/15084577/20240424-025631.000.p7d.zip)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by gandalfthewhite19890404** [comment]
Unimplemented - sceAudiodecInitLibrary

**Comment by Emulator-Team-2** [comment]
## Update:

### Please, describe what you get

The game no longer crashes right after launch.
Now the game freezes before the opening movie starts playing.

With this error:
```
Error:ParseRIFF: ffmpeg failed to read passed data: -1094995529
```

### Game version you are using

01.05

### Current game status

Intro

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

5ea4a19d6169e9bfa956279b0844b84949f04418

### Upload your log there

[20240423-233535.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/15083348/20240423-233535.000.p7d.zip)

### Upload your screenshots there

<details> 
<summary>(Intro - screenshots)</summary>

![1](https://github.com/SysRay/psOff_compatibility/assets/38318848/617952ef-7887-4571-b552-7228388ab848)

![2](https://github.com/SysRay/psOff_compatibility/assets/38318848/d57b5499-3c71-499d-a920-24f013ecfe6f)

</details>

**Comment by igor725** [comment]
> With this error:
> 
> ```
> Error:ParseRIFF: ffmpeg failed to read passed data: -1094995529
> ```

This error means `AVERROR_INVALIDDATA`, data passed to decoder is invalid. But this error can't be reason of this freeze... probably.

**Comment by Emulator-Team-2** [comment]
@igor725 
With (libSceNgs2) in sce_module, the game goes to the main menu without playing the opening movie.

**Comment by Emulator-Team-2** [comment]
## Update:

The game now goes to the main menu without (libSceNgs2).
But it crashes with a different error.

(On the character select screen):
```
Critical Error:0x28200134 not in m_deviceMemoryList
Exiting
unknown Imagedim for 6
```

**Emulator version:** v.0.5-preview-0
**psOff-libs version:**
63dd5ad3b5b3be2a67e63301dccd92fcf426ba3d

Log:
[20240425-212934.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/15119816/20240425-212934.000.p7d.zip)

<details> 
<summary>(Screenshots)</summary>

![1](https://github.com/SysRay/psOff_compatibility/assets/38318848/2c7230cc-64fd-4eb4-9c6f-818b2c277a60)

</details>

## 
Other issues:
- Incorrect colors.
- The opening movie still doesn't play after the (intro / logo).

**Comment by Emulator-Team-2** [comment]
## Update:

The game still crashes on the character selection screen.
But now with a different error:
```
Critical Error:0x00000200 not in m_deviceMemoryList
Exiting
Assertion failed: id, file D:\a\psOff\psOff\tools\sb2spirv\lib\src/spirv/spirv-builder.hpp, line 329
```
```
Critical Error:Assertion failed: numElements > 16, file D:\a\psOff\psOff\tools\sb2spirv\lib\src/typeId.h, line 200
```

**Current game status:** Intro.

**Emulator version:** v.0.5-preview-0
**psOff-libs version:**
8971baae0d5e6cdde85e2c16f062db7aa079804a

Log:
[20240428-031521.000.zip](https://github.com/SysRay/psOff_compatibility/files/15140437/20240428-031521.000.zip)
[20240428-032101.000.zip](https://github.com/SysRay/psOff_compatibility/files/15140444/20240428-032101.000.zip)

**Comment by Emulator-Team-2** [comment]
## Update:

The game now freezes again before the opening movie starts playing.
```
Error:ParseRIFF: ffmpeg failed to read passed data: -1094995529
Error:todo sceSystemServiceDisableMusicPlayer
Error:todo handle attributes
```

**Current game status:** Intro.

**Renderer version:** v.0.5-nightly_04.05.24  
**psOff version:**
4161cbba3b8799559d8c0a5def574f4a6c483caa

Log:
[20240512-130341.000.zip](https://github.com/SysRay/psOff_compatibility/files/15285972/20240512-130341.000.zip)
