### ISSUE TITLE
[CUSA00900]: Bloodborne™

### ISSUE THREAD

**Issue by Digote** [SysRay/psOff_compatibility#74]
### Please, describe what you get

The game goes on an infinite loop with this black screen.

Error:todo sceNpSetContentRestriction
Console:sceNetBind Failed: errno=0x0

### Game version you are using

1.0

### Current game status

Nothing

### Your emulator version

v0.5-preview-0

### psOff-libs version you are using

https://github.com/SysRay/psOff_public/actions/runs/8710509714

### Upload your log there

[20240416-155702.000.zip](https://github.com/SysRay/psOff_compatibility/files/15001496/20240416-155702.000.zip)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by Ordinary205** [comment]
Try waiting for bloodborne to load around 5 or 10 minutes, and then you'll get the correct results.

**Comment by Digote** [comment]
Thanks for the tip, follow the entire log until the console actually crashes.

Selected GPU:NVIDIA GeForce RTX 4060 Ti api:1.3.277
Error:todo sceNpSetContentRestriction
Console:sceNetBind Failed: errno=0x0
Error:todo sceNpSetNpTitleId
Error:todo sceNpMatching2Initialize
Error:todo sceNpRegisterStateCallback
Error:todo sceNpRegisterGamePresenceCallback
Critical Error:Unhandled epoll event SCE_NET_EPOLLDESCID
Exiting
Error:TODO: scePlayGoGetChunkId
Error:TODO: scePlayGoSetInstallSpeed
saving config files
shutting down VideoOut
deinit Graphics| closed: command buffer watcher
deinit Graphics| done
deinit Graphics| closing command processors
-> destruct CommandProcessor[0]
<- destruct CommandProcessor[0]
deinit Graphics| done
deinit Graphics| closing manager
-> deinit ShaderManager
<- deinit ShaderManager
-> deinit SamplerManager
<- deinit SamplerManager
-> deinit PipelineManager


**Upload your log there**

[20240418-143425.000.p7d.zip](https://github.com/SysRay/psOff_compatibility/files/15028464/20240418-143425.000.p7d.zip)
