### ISSUE TITLE
[CUSA 04518]: Project Diva X

### ISSUE THREAD

**Issue by Jomanakk** [SysRay/psOff_compatibility#77]
### Please, describe what you get

You get a black screen, the game just doesn't boot

### Game version you are using

v1.0

### Current game status

Nothing

### Your emulator version

v.0.4-beta

### Upload your log there

No logs 

### Upload your screenshots there

![image](https://github.com/SysRay/psOff_compatibility/assets/107001229/a726cff3-883e-46d0-8969-282bf73d7851)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by GamingDucking** [comment]
Already posted:https://github.com/SysRay/psOff_compatibility/issues/17.
Close the issue.
