### ISSUE TITLE
[CUSA03627]: The Last Guardian

### ISSUE THREAD

**Issue by Digote** [SysRay/psOff_compatibility#78]
### Please, describe what you get

Running this title results in a Critical Error:Stack check fail

Console:======================================================
Console:  trico main() start...
Console:======================================================
Critical Error:Stack check fail
Exiting

### Game version you are using

1.0

### Current game status

Nothing

### Your emulator version

v0.5-preview-0

### psOff-libs version you are using

https://github.com/SysRay/psOff_public/actions/runs/8711437652

### Upload your log there

[20240417-124735.000.zip](https://github.com/SysRay/psOff_compatibility/files/15013428/20240417-124735.000.zip)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by igor725** [comment]
Game status update:
```
Console:======================================================
Console:  trico main() start...
Console:======================================================
Console:[Memblock statistics(Type)]
Console:RenderTarget     n=0        size=0KB
Console:Depth/Stencil    n=0        size=0KB
Console:Texture          n=0        size=0KB
Console:Buffer           n=0        size=0KB
Console:CommandBuffer    n=0        size=0KB
Console:Shader           n=0        size=0KB
Console:Other            n=0        size=0KB
Console:Chunk stats [Use 0][Vacant 3][Free 81917], Largest Block 2816.000 MB
Console:Used 0.000 MB, Free 2816.000 MB, Total 2816.000 MB,
Console:[Memblock statistics(Type)]
Console:RenderTarget     n=0        size=0KB
Console:Depth/Stencil    n=0        size=0KB
Console:Texture          n=0        size=0KB
Console:Buffer           n=0        size=0KB
Console:CommandBuffer    n=0        size=0KB
Console:Shader           n=0        size=0KB
Console:Other            n=0        size=0KB
Console:Chunk stats [Use 0][Vacant 3][Free 16381], Largest Block 96.000 MB
Console:Used 0.000 MB, Free 96.000 MB, Total 96.000 MB,
Critical Error:Missing Symbol| Name:A+uGq+3KFtQ#E#F Lib:libSceGnmDriver(ver:1) Mod:libSceGnmDriver(major:1 minor:1)
Exiting
```

Missing symbol: sceGnmMapComputeQueueWithPriority
