### ISSUE TITLE
[CUSA00362]: Alien: Isolation™

### ISSUE THREAD

**Issue by GAMERRPCS3** [SysRay/psOff_compatibility#89]
### Please, describe what you get

Nothing - missing symbol.

Error:todo sceAppContentGetAddcontInfoList
Error:todo sceAppContentGetAddcontInfoList
Console:P:\graphics\code\graphics\gfx_api_gnm.cpp(1866): error in Gfx_CreateDevice(): breakpoint hook
Error:todo sceCameraOpen
Error:0x140022fc7
Error:0x14001eb37
Error:0x140017163
Error:0x00611858
Critical Error:Missing Symbol| Name:ZE6RNL+eLbk#F#C Lib:libSceLibcInternal(ver:1) Mod:libSceLibcInternal(major:1 minor:1)
Exiting

### Game version you are using

01.00

### Current game status

Nothing

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

a2fc208181eff1a38af873a9797f49cea260eb40

### Upload your log there

[633oqp4jup5yh9h8.zip](https://github.com/SysRay/psOff_compatibility/files/15025600/633oqp4jup5yh9h8.zip)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by igor725** [comment]
Should progress further with <https://github.com/SysRay/psOff_public/actions/runs/8772042055>. But it seems like the game will crash afterwards because of some unimplemented GNM feature, so don't expect much.

**Comment by GAMERRPCS3** [comment]
Retest, here is the current error.

![Capture d’écran 2024-04-21 140322](https://github.com/SysRay/psOff_compatibility/assets/121258975/21abb431-a985-41b2-b604-e83bd8d403d8)
[azjtw51eiu7c55gi.zip](https://github.com/SysRay/psOff_compatibility/files/15051772/azjtw51eiu7c55gi.zip)

**Comment by igor725** [comment]
Retest with <https://github.com/igor725/psOff_public/actions/runs/8772888997>

**Comment by gandalfthewhite19890404** [comment]
Resolved - tanf

**Comment by GAMERRPCS3** [comment]
Retest

Critical Error:Missing Symbol| Name:hHA1frlMxYE#D#E Lib:libSceCamera(ver:1) Mod:libSceCamera(major:1 minor:1)
Exiting
[xaauaepwt0pr33wq.zip](https://github.com/SysRay/psOff_compatibility/files/15052609/xaauaepwt0pr33wq.zip)

**Comment by gandalfthewhite19890404** [comment]
Resolved - sceCameraGetCalibData

**Comment by GAMERRPCS3** [comment]
Retest 

Critical Error:Missing Symbol| Name:DYdXC4Ixa4s#G#H Lib:libSceFace(ver:1) Mod:libSceFace(major:1 minor:1)
Exiting

[xfhrt5jtunp082ll.zip](https://github.com/SysRay/psOff_compatibility/files/15142495/xfhrt5jtunp082ll.zip)

**Comment by GAMERRPCS3** [comment]
Retest 
Error:Unknown controller type "gamepad" falling back to "SDL"
Error:Unknown controller type "gamepad" falling back to "SDL"
Error:Unknown controller type "gamepad" falling back to "SDL"
Error:Unknown controller type "gamepad" falling back to "SDL"
Error:todo sceCameraOpen
Error:todo sceDepthQueryMemory
Error:todo sceDepthInitialize
Error:todo sceCameraStop
Error:todo sceNpSetContentRestriction
Error:todo sceNpSetNpTitleId
Error:todo sceNpRegisterStateCallback
Error:todo sceNpRegisterGamePresenceCallback
Error:Couldn't Allocate Host Memory: 0x110020000|16384 type:51 result:VK_ERROR_OUT_OF_DEVICE_MEMORY
Error:free Error| start:0x160020000 len:0x00000008 != start:0x160020000 len:0x00004000
Error:Couldn't Allocate Host Memory: 0x110030000|16384 type:51 result:VK_ERROR_OUT_OF_DEVICE_MEMORY
Error:free Error| start:0x160020000 len:0x00000008 != start:0x160020000 len:0x00004000
Error:Couldn't Allocate Host Memory: 0x110040000|16384 type:51 result:VK_ERROR_OUT_OF_DEVICE_MEMORY
Error:free Error| start:0x160020000 len:0x000000ac != start:0x160020000 len:0x00004000
Error:offset:0x0003104e  base:0x11e80000        libc.prx
Critical Error:Access violation: Write at addr:0x11eb104e info:0xffffffffffffffff , module base:0x11e80000 libc.prx
Exiting
[a4pex6lrlsx1lf2h.zip](https://github.com/SysRay/psOff_compatibility/files/15188511/a4pex6lrlsx1lf2h.zip)
