### ISSUE TITLE
[CUSA15128]: DYSMANTLE

### ISSUE THREAD

**Issue by GAMERRPCS3** [SysRay/psOff_compatibility#90]
### Please, describe what you get

the game starts with the introduction and gets to the menu, and crashes upon entering gameplay.

Error:Exception 0x7ffbbbd8146c
Error:0x140022fc7
Error:0x14001eb37
Error:0x140019447
Error:0x140063079
Error:0x7ffbdd8923af
Error:0x7ffbdd8414b4
Error:0x7ffbdd890ebe
Error:0x7ffbbbd8146c
Error:0x7ffbc40716d0
Error:0x108a8a75          in eboot.bin
Error:Access violation: Read 0x00000000
saving config files
shutting down VideoOut
deinit Graphics| closed: command buffer watcher
deinit Graphics| done
deinit Graphics| closing command processors
-> destruct CommandProcessor[0]
<- destruct CommandProcessor[0]
deinit Graphics| done
deinit Graphics| closing manager
-> deinit ShaderManager
<- deinit ShaderManager
-> deinit SamplerManager
<- deinit SamplerManager
-> deinit PipelineManager

### Game version you are using

01.08

### Current game status

Intro

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

a2fc208181eff1a38af873a9797f49cea260eb40

### Upload your log there

[558heljsk5mt47r6.zip](https://github.com/SysRay/psOff_compatibility/files/15028420/558heljsk5mt47r6.zip)

### Upload your screenshots there

![Capture d’écran 2024-04-18 193119](https://github.com/SysRay/psOff_compatibility/assets/121258975/58cd9670-b482-4c24-834b-22d7da7639c3)
![Capture d’écran 2024-04-18 193127](https://github.com/SysRay/psOff_compatibility/assets/121258975/9f764e68-590d-406e-9b61-f42cd42dd7b0)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by igor725** [comment]
Dysmantle is ingame now.
Missing sound is expected, since libSceNgs2 is not implemented yet.

https://github.com/SysRay/psOff_compatibility/assets/40758030/e4cbd715-7771-4c5d-b6cd-52597043cc13

**Comment by GAMERRPCS3** [comment]
> Dysmantle is ingame now (since [SysRay/psOff_public#127](https://github.com/SysRay/psOff_public/pull/127)).
> Missing sound is expected, since libSceNgs2 is not implemented yet.
> The game won't boot without v1.08 patch installed tho.
> Bloom effect and DoF should be turned OFF.
omg nice

**Comment by yaya54840** [comment]
Hi
![Capture d'écran 2024-06-02 172242](https://github.com/SysRay/psOff_compatibility/assets/47884186/a769e7e2-57c4-41b9-a9b5-88123dbafe81)

Graphics are great now
