### ISSUE TITLE
[CUSA15493]: Ghostbusters: The Video Game Remastered

### ISSUE THREAD

**Issue by Ordinary205** [SysRay/psOff_compatibility#91]
### Please, describe what you get

This game does boot and displays an image. However, the FMW does not load correctly, and sadly the game gets stuck while trying to press x. Making it impossible to progress during the menu.

Error:TODO sceVideoOutWaitVblank
Error:TODO sceVideoOutWaitVblank
Error:TODO sceVideoOutWaitVblank
Error:TODO sceVideoOutWaitVblank
Error:TODO sceVideoOutWaitVblank
Error:TODO sceVideoOutWaitVblank
Console:my_output_thread : audio out thread finished.
Error:openCodecContext: no audio stream
Error:todo video loop

### Game version you are using

v1.00

### Current game status

Intro

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

a7d32f1727082f6b20c2bc9595f1086ae330e68f

### Upload your log there

[20240418-223015.000.zip](https://github.com/SysRay/psOff_compatibility/files/15029118/20240418-223015.000.zip)

### Upload your screenshots there

![ghostbusters intro](https://github.com/SysRay/psOff_compatibility/assets/125112932/58e4b441-08a4-409b-a109-bb48477370eb)

Once this image shows up, it stops at todo video loop.
![Ghostbusters](https://github.com/SysRay/psOff_compatibility/assets/125112932/922d9a1d-3c99-47e4-b8b8-a749f4887f7a)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by Ordinary205** [comment]
After retesting, the game now goes further during menus without FMW, and crashes before ingame.
![Ghostbusters](https://github.com/SysRay/psOff_compatibility/assets/125112932/cb2ba1e9-ff6e-4667-83ae-749453e5a3d4)
[20240426-062247.000.zip](https://github.com/SysRay/psOff_compatibility/files/15124619/20240426-062247.000.zip)

**Comment by AussiePlick** [comment]
Date is 09.06.2024
If you leave the beginning screens a minute or so you can now get into the game. Has full audio, but black screen. 
FPS = 30 - 58
The version I am using is 0.6     08.06.2024.
My gfx card is geforce 3060 TI and using AMD 12 core cpu.
32 gig ram
