### ISSUE TITLE
[CUSA06212]: RESIDENT EVIL REVELATIONS

### ISSUE THREAD

**Issue by GAMERRPCS3** [SysRay/psOff_compatibility#99]
### Please, describe what you get

Nothing - missing symbol.

Critical Error:Missing Symbol| Name:OOrLKB0bSDs#BDo#u Lib:libSceSharePlay(ver:1) Mod:libSceSharePlay(major:0 minor:0)

### Game version you are using

01.00

### Current game status

Nothing

### Your emulator version

v.0.5-preview-0

### psOff-libs version you are using

276936ca129c0f9d47ab59d2ba37f6ed91bfa4b2

### Upload your log there

[h6fwd26e713cu0nx.zip](https://github.com/SysRay/psOff_compatibility/files/15040132/h6fwd26e713cu0nx.zip)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by igor725** [comment]
Should progress further with <https://github.com/SysRay/psOff_public/actions/runs/8772042055>

**Comment by GAMERRPCS3** [comment]
Retest, here is the current error.

![Capture d’écran 2024-04-21 140911](https://github.com/SysRay/psOff_compatibility/assets/121258975/22d34815-3531-43c3-ad5c-2c12d80f0e7a)
[ys18bql1dephit2f.zip](https://github.com/SysRay/psOff_compatibility/files/15051818/ys18bql1dephit2f.zip)

**Comment by gandalfthewhite19890404** [comment]
Resolved - sceSharePlayGetCurrentConnectionInfo
